homeassistant:
  name:       !secret home_name
  latitude:   !secret home_latitude
  longitude:  !secret home_longitude
  elevation:  !secret home_elevation
  time_zone:  !secret home_timezone
  customize:  !include_dir_merge_named includes/customizations
  packages:   !include_dir_named includes/packages
  unit_system: metric
  allowlist_external_dirs:
    - '/config/downloads'

config:
api:
system_health:
conversation:
history:
wake_on_lan:
zeroconf:
mobile_app:
map:
sun:
ffmpeg:
stream:
energy:

discovery:
  ignore:
    - homekit

frontend:
  themes: !include_dir_merge_named themes

http:
  ip_ban_enabled: true
  login_attempts_threshold: 5
  use_x_forwarded_for: true
  trusted_proxies:
    - 127.0.0.1
    - ::1

system_log:
  fire_event: true

tts:
  - platform: google_translate
    service_name: google_say
    language: 'ru'

switch:             !include_dir_merge_list includes/switches
sensor:             !include_dir_merge_list includes/sensors
binary_sensor:      !include_dir_merge_list includes/binary_sensors
template:           !include_dir_merge_list includes/template
light:              !include_dir_merge_list includes/lights
climate:            !include_dir_merge_list includes/climate
automation manual:  !include_dir_merge_list includes/automations
automation ui:      !include automations.yaml
script:             !include_dir_merge_named includes/scripts
lovelace:           !include includes/lovelace.yaml
recorder:           !include includes/recorder.yaml
logbook:            !include includes/logbook.yaml
influxdb:           !include includes/influxdb.yaml
logger:             !include includes/logger.yaml
#mqtt:               !include includes/mqtt.yaml
device_tracker:     !include includes/device_tracker.yaml
telegram_bot:       !include includes/telegram_bot.yaml
notify:             !include includes/notify.yaml
group:              !include includes/groups.yaml
media_player:       !include includes/media_player.yaml
input_boolean:      !include includes/input_boolean.yaml
input_number:       !include includes/input_number.yaml
input_select:       !include includes/input_select.yaml
input_text:         !include includes/input_text.yaml
panel_iframe:       !include includes/panel_iframe.yaml
timer:              !include includes/timer.yaml
counter:            !include includes/counter.yaml
camera:             !include includes/camera.yaml
scene:              !include includes/scenes.yaml
rest_command:       !include includes/rest_command.yaml

# custom integration
python_script:
watchman:           !include includes/watchman.yaml
xiaomi_gateway3:    !include includes/gateway3.yaml

#sonoff:
#  username: !secret sonoff_username
#  password: !secret sonoff_password
#  mode: local
#  reload: always


