- platform: xiaomi_miio
  name: living_room_spot_left_1
  host: !secret living_room_spot_left_1_ip
  token: !secret living_room_spot_left_1_token
  model: philips.light.downlight

- platform: xiaomi_miio
  name: living_room_spot_left_2
  host: !secret living_room_spot_left_2_ip
  token: !secret living_room_spot_left_2_token
  model: philips.light.downlight

- platform: xiaomi_miio
  name: living_room_spot_left_3
  host: !secret living_room_spot_left_3_ip
  token: !secret living_room_spot_left_3_token
  model: philips.light.downlight

#- platform: xiaomi_miio
# name: living_room_spot_right_1
# host: !secret living_room_spot_right_1_ip
# token: !secret living_room_spot_right_1_token
# model: philips.light.downlight

- platform: xiaomi_miio
  name: wc_spot_1
  host: !secret wc_spot_1_ip
  token: !secret wc_spot_1_token
  model: philips.light.downlight

- platform: xiaomi_miio
  name: wc_spot_2
  host: !secret wc_spot_2_ip
  token: !secret wc_spot_2_token
  model: philips.light.downlight

