- alias: "Switch balcony"
  initial_state: true
  trigger:
    - platform: state
      entity_id: sensor.0x00158d000183dd12_action
      to: 'single'
    - platform: state
      entity_id: sensor.0x00158d000183d2d5_action
      to: 'single'
  action:
    service: switch.toggle
    entity_id:
      - switch.0x00158d00022ab4bf
      - switch.0x00158d0001f9aa3
      - switch.0x00158d0002114338

- alias: "Turn on led strip on balcony"
  initial_state: true
  trigger:
    - platform: numeric_state
      entity_id: sensor.0x54ef4410000c1dec_illuminance
      below: 10
  condition:
    - condition: state
      entity_id: light.balcony_strip
      state: 'off'
  action:
    - service: light.turn_on
      entity_id: light.balcony_strip
      data:
        brightness_pct: 10

- alias: "Turn off led strip on balcony"
  initial_state: true
  trigger:
    - platform: time
      at:
        - '00:15:00'
        - '01:15:00'
  action:
    - service: light.turn_off
      entity_id: light.balcony_strip

