- alias: "Switch balcony"
  initial_state: 'on'
  trigger:
    - platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: binary_sensor.wall_switch_158d000183dd12
        click_type: single
    - platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: binary_sensor.wall_switch_158d000183d2d5
        click_type: single
  action:
    service: switch.toggle
    entity_id:
      - switch.wall_switch_ln_158d00022ab4bf
      - switch.wall_switch_ln_158d0001f9aa37
      - switch.wall_switch_ln_158d0002114338

- alias: "Turn led strip on balcony"
  initial_state: 'on'
  trigger:
    platform: sun
    event: sunset
    offset: '+00:10:00'
  action:
    service: light.turn_on
    entity_id: light.balcony_strip
    data_template:
      brightness_pct: 20
#     kelvin: 6500

- alias: "Turn off led strip on balcony"
  initial_state: 'on'
  trigger:
    - platform: time
      at: '00:15:00'
    - platform: time
      at: '01:15:00'
  action:
    service: light.turn_off
    entity_id: light.balcony_strip

