- alias: "Switch balcony"
  initial_state: true
  trigger:
    - platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: sensor.0x158d000183dd12_action
        click_type: single
    - platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: sensor.0x158d000183d2d5_action
        click_type: single
  action:
    service: switch.toggle
    entity_id:
      - switch.0x158d00022ab4bf_switch
      - switch.0x158d0001f9aa37_switch
      - switch.0x158d0002114338_switch

- alias: "Turn led strip on balcony"
  initial_state: true
  trigger:
    - platform: numeric_state
      entity_id: sensor.0x54ef4410000c1dec_illuminance
      below: 10
  condition:
    - condition: state
      entity_id: light.balcony_strip
      state: 'off'
  action:
    - service: light.turn_on
      entity_id: light.balcony_strip
      data:
        brightness_pct: 20

- alias: "Turn off led strip on balcony"
  initial_state: true
  trigger:
    - platform: time
      at:
        - '00:15:00'
        - '01:15:00'
  action:
    - service: light.turn_off
      entity_id: light.balcony_strip

