# Bathroom
# Light
- alias: "Turn on light in Bathroom on conditions"
  initial_state: true
  trigger:
    - platform: state
      entity_id: binary_sensor.0x00158d0002fd4381_contact
      to: 'on'
    - platform: state
      entity_id: binary_sensor.0x00158d00044a26ba_occupancy
      from: 'off'
      to: 'on'
    - platform: state
      entity_id: binary_sensor.0x54ef441000268428_occupancy
#     from: 'off'
      to: 'on'
  condition:
    - condition: state
      entity_id: switch.0x00158d00022a8150_left
      state: 'off'
  action:
    - service: switch.turn_on
      entity_id: switch.0x00158d00022a8150_left

- alias: "Turn on Bathroom timer"
  initial_state: true
  trigger:
    - platform: state
      entity_id: switch.0x00158d00022a8150_left
      to: 'on'
  action:
    - service: timer.cancel
      entity_id: timer.bathroom_light
    - service: timer.start
      entity_id: timer.bathroom_light

- alias: "Reset Bathroom timer on conditions"
  initial_state: true
  trigger:
    - platform: state
      entity_id: binary_sensor.0x00158d0002fd4381_contact
      to: 'off'
    - platform: state
      entity_id: binary_sensor.0x00158d00044a26ba_occupancy
      from: 'off'
      to: 'on'
    - platform: state
      entity_id: binary_sensor.0x54ef441000268428_occupancy
#     from: 'off'
      to: 'on'
  condition:
    - condition: state
      entity_id: switch.0x00158d00022a8150_left
      state: 'on'
  action:
    - service: timer.cancel
      entity_id: timer.bathroom_light
    - service: timer.start
      entity_id: timer.bathroom_light

- alias: "Turn off light in Bathroom on conditions"
  initial_state: true
  trigger:
    - platform: event
      event_type: timer.finished
      event_data:
        entity_id: timer.bathroom_light
  condition:
    - condition: state
      entity_id: input_boolean.auto_turn_off_lights
      state: 'on'
    - condition: state
      entity_id: switch.0x00158d00022a8150_left
      state: 'on'
    - condition: state
      entity_id: binary_sensor.0x00158d0002fd4381_contact
      state: 'off'
  action:
    - service: switch.turn_off
      entity_id: switch.0x00158d00022a8150_left

- alias: "Turn off Bathroom timer if light is off"
  initial_state: true
  trigger:
    - platform: state
      entity_id: switch.0x00158d00022a8150_left
      to: 'off'
  action:
    - service: timer.cancel
      entity_id: timer.bathroom_light

# FAN
- alias: "Turn off Bathroom fan"
  initial_state: true
  trigger:
    - platform: state
      entity_id: switch.0x54ef4410001ad4c2_right
      to: 'off'
    - platform: event
      event_type: timer.finished
      event_data:
        entity_id: timer.bathroom_fan
  action:
    - service: switch.turn_off
      entity_id: switch.0x54ef4410001ad4c2_right
    - service: timer.cancel
      entity_id: timer.bathroom_fan

- alias: "Turn on Bathroom fan"
  initial_state: true
  trigger:
    - platform: state
      entity_id: switch.0x54ef4410001ad4c2_right
      to: 'on'
    - platform: numeric_state
      entity_id: sensor.0x00158d000273011f_humidity
      above: 68
  action:
    - service: switch.turn_on
      entity_id: switch.0x54ef4410001ad4c2_right
    - service: timer.cancel
      entity_id: timer.bathroom_fan
    - service: timer.start
      entity_id: timer.bathroom_fan

- alias: "Turn on Bathroom fan on schedule"
  initial_state: true
  trigger:
    - platform: time
      at:
        - '07:45'
        - '13:00'
        - '18:00'
  condition:
    - condition: state
      entity_id: input_boolean.auto_fan
      state: 'on'
    - condition: state
      entity_id: switch.0x54ef4410001ad4c2_right
      state: 'off'
  action:
    - service: switch.turn_on
      entity_id: switch.0x54ef4410001ad4c2_right
    - service: timer.cancel
      entity_id: timer.bathroom_fan
    - service: timer.start
      entity_id: timer.bathroom_fan
      data:
        duration: 00:05:00

# Start HA
- alias: "Start Bathroom timer if not starting"
  initial_state: true
  trigger:
    - platform: homeassistant
      event: start
  condition:
    - condition: state
      entity_id: switch.0x00158d00022a8150_left
      state: 'on'
  action:
    - service: timer.start
      entity_id: timer.bathroom_light

- alias: "Start Bathroom fan timer if not starting"
  initial_state: true
  trigger:
    - platform: homeassistant
      event: start
  condition:
    - condition: state
      entity_id: switch.0x54ef4410001ad4c2_right
      state: 'on'
  action:
    - service: timer.start
      entity_id: timer.bathroom_fan

