# Bathroom
# Light
- alias: "Turn on light in Bathroom on conditions"
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: binary_sensor.door_window_sensor_158d0002fd4381
      to: 'on'
    - platform: event
      event_type: xiaomi_aqara.motion
      event_data:
        entity_id: binary_sensor.motion_sensor_158d00044a26ba
  condition:
    - condition: state
      entity_id: switch.wall_switch_ln_left_158d00022a8150
      state: 'off'
  action:
    - service: switch.turn_on
      entity_id: switch.wall_switch_ln_left_158d00022a8150
    - service: timer.cancel
      entity_id: timer.bathroom_light
    - service: timer.start
      entity_id: timer.bathroom_light

- alias: "Turn on Bathroom timer"
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: switch.wall_switch_ln_left_158d00022a8150
      to: 'on'
  action:
    - service: timer.cancel
      entity_id: timer.bathroom_light
    - service: timer.start
      entity_id: timer.bathroom_light

- alias: "Reset Bathroom timer on conditions"
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: binary_sensor.door_window_sensor_158d0002fd4381
      to: 'off'
    - platform: event
      event_type: xiaomi_aqara.motion
      event_data:
        entity_id: binary_sensor.motion_sensor_158d00044a26ba
  condition:
    - condition: state
      entity_id: switch.wall_switch_ln_left_158d00022a8150
      state: 'on'
  action:
    - service: timer.cancel
      entity_id: timer.bathroom_light
    - service: timer.start
      entity_id: timer.bathroom_light

- alias: "Turn off light in Bathroom on conditions"
  initial_state: 'on'
  trigger:
    - platform: event
      event_type: timer.finished
      event_data:
        entity_id: timer.bathroom_light
  condition:
    - condition: state
      entity_id: input_boolean.auto_turn_off_lights
      state: 'on'
    - condition: state
      entity_id: switch.wall_switch_ln_left_158d00022a8150
      state: 'on'
    - condition: state
      entity_id: binary_sensor.door_window_sensor_158d0002fd4381
      state: 'off'
  action:
    - service: switch.turn_off
      entity_id: switch.wall_switch_ln_left_158d00022a8150

- alias: "Turn off Bathroom timer if light is off"
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: switch.wall_switch_ln_left_158d00022a8150
      to: 'off'
  action:
    - service: timer.cancel
      entity_id: timer.bathroom_light

# FAN
- alias: "Turn off Bathroom fan"
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: switch.sonoff_br_relay_1
      to: 'off'
    - platform: event
      event_type: timer.finished
      event_data:
        entity_id: timer.bathroom_fan
  action:
    - service: switch.turn_off
      entity_id: switch.sonoff_br_relay_1
    - service: timer.cancel
      entity_id: timer.bathroom_fan

- alias: "Turn on Bathroom fan"
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: switch.sonoff_br_relay_1
      to: 'on'
    - platform: numeric_state
      entity_id: sensor.humidity_158d000273011f
      above: 68
  action:
    - service: switch.turn_on
      entity_id: switch.sonoff_br_relay_1
    - service: timer.cancel
      entity_id: timer.bathroom_fan
    - service: timer.start
      entity_id: timer.bathroom_fan

- alias: "Turn on Bathroom fan on schedule"
  initial_state: 'on'
  trigger:
    - platform: time
      at: '07:45'
    - platform: time
      at: '13:00'
    - platform: time
      at: '18:00'
  condition:
    - condition: state
      entity_id: input_boolean.auto_fan
      state: 'on'
    - condition: state
      entity_id: switch.sonoff_br_relay_1
      state: 'off'
  action:
    - service: switch.turn_on
      entity_id: switch.sonoff_br_relay_1
    - service: timer.cancel
      entity_id: timer.bathroom_fan
    - service: timer.start
      entity_id: timer.bathroom_fan
      data_template:
        duration: 00:05:00

# Start HA
- alias: "Start Bathroom timer if not starting"
  initial_state: 'on'
  trigger:
    - platform: homeassistant
      event: start
  condition:
    - condition: state
      entity_id: switch.wall_switch_ln_left_158d00022a8150
      state: 'on'
  action:
    - service: timer.start
      entity_id: timer.bathroom_light

- alias: "Start Bathroom fan timer if not starting"
  initial_state: 'on'
  trigger:
    - platform: homeassistant
      event: start
  condition:
    - condition: state
      entity_id: switch.sonoff_br_relay_1
      state: 'on'
  action:
    - service: timer.start
      entity_id: timer.bathroom_fan

