- alias: "Set brightness for lamp in bedroom"
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: light.bedroom_lamp
    from: 'off'
    to: 'on'
  action:
    - service: yeelight.set_mode
      data:
        entity_id: light.bedroom_lamp
        mode: normal
    - service: yeelight.set_color_temp_scene
      data:
        entity_id: light.bedroom_lamp
        brightness: 70
        kelvin: 4000
