- alias: check camera1
  initial_state: false
  trigger:
    - platform: state
      entity_id: binary_sensor.camera1
      to: "off"
  action:
    - service: notify.telegram
      data:
        message: "\U00002620 camera1 is not working"

- alias: "check camera1 on start"
  initial_state: false
  trigger:
    - platform: homeassistant
      event: start
  condition:
    - condition: state
      entity_id: binary_sensor.camera1
      state: 'off'
    - condition: state
      entity_id: sensor.ups_status_data
      state: 'OL'
  action:
    - service: notify.telegram
      data:
        message: "\U00002620 camera1 is not working 2"
    - service: switch.turn_off
      entity_id: switch.bw_plug_2_relay_usb
    - delay: '00:00:05'
    - service: switch.turn_on
      entity_id: switch.bw_plug_2_relay_usb
