- alias: ha1_server_off
  initial_state: true
  trigger:
    - platform: state
      entity_id: sensor.ha1_uptime
      to: "unavailable"
      for: "00:02:00"
  action:
    - service: notify.telegram
      data:
        message: "\U00002620 {{ states.sensor.date_time.state }} | HA1 is not working"

- alias: ha1_server_on
  initial_state: true
  trigger:
    - platform: state
      entity_id: sensor.ha1_uptime
      from: "unavailable"
  action:
    - service: notify.telegram
      data:
        message: "\U00002705 {{ states.sensor.date_time.state }} | HA1 is now working"

- alias: ha2_server_off
  initial_state: true
  trigger:
    - platform: state
      entity_id: sensor.ha2_uptime
      to: "unavailable"
      for: "00:02:00"
  action:
    - service: notify.telegram
      data:
        message: "\U00002620 {{ states.sensor.date_time.state }} | HA2 is not working"

- alias: ha2_server_on
  initial_state: true
  trigger:
    - platform: state
      entity_id: sensor.ha2_uptime
      from: "unavailable"
  action:
    - service: notify.telegram
      data:
        message: "\U00002705 {{ states.sensor.date_time.state }} | HA2 is now working"

