# Hallway
- alias: "Turn on lights in Hallway on conditions"
  initial_state: true
  trigger:
    platform: state
    entity_id: binary_sensor.0x00158d00032b7db7_contact
    to: 'on'
  condition:
    condition: state
    entity_id: switch.0x00158d0002112b1e
    state: 'off'
    for:
      minutes: 2
  action:
    - service: switch.turn_on
      entity_id:
        - switch.0x00158d0002112b1e
        - switch.0x00158d0002113ace
    - service: timer.cancel
      entity_id: timer.hallway_light
    - service: timer.start
      entity_id: timer.hallway_light

- alias: "Front door opened"
  initial_state: true
  trigger:
    platform: state
    entity_id: binary_sensor.0x00158d00032b7db7_contact
    to: 'on'
  action:
    - service: notify.telegram
      data:
        message: "\U0001F6AA The front door opened"

- alias: "Door opened more than"
  initial_state: true
  trigger:
    - platform: state
      entity_id: binary_sensor.0x00158d00032b7db7_contact
      to: 'on'
      for:
        minutes: 2
    - platform: state
      entity_id: binary_sensor.0x00158d00032b7db7_contact
      to: 'on'
      for:
        minutes: 5
    - platform: state
      entity_id: binary_sensor.0x00158d00032b7db7_contact
      to: 'on'
      for:
        minutes: 10
  action:
    - service: notify.telegram
      data:
        message: "\U0001F6AA The door is open for more than {{ trigger.for }}"

- alias: "Turn on light in Hallway sw1"
  initial_state: true
  trigger:
    platform: state
    entity_id: switch.0x00158d0002112b1e
    from: 'off'
    to: 'on'
  condition:
    condition: state
    entity_id: switch.0x00158d0002113ace
    state: 'off'
  action:
    - service: switch.turn_on
      entity_id: switch.0x00158d0002113ace
    - service: timer.cancel
      entity_id: timer.hallway_light
    - service: timer.start
      entity_id: timer.hallway_light

- alias: "Turn off light in Hallway sw1"
  initial_state: true
  trigger:
    platform: state
    entity_id: switch.0x00158d0002112b1e
    from: 'on'
    to: 'off'
  action:
    - service: switch.turn_off
      entity_id: switch.0x00158d0002113ace
    - service: timer.cancel
      entity_id: timer.hallway_light

- alias: "Turn on light in Hallway sw2"
  initial_state: true
  trigger:
    platform: state
    entity_id: switch.0x00158d0002113ace
    from: 'off'
    to: 'on'
  condition:
    condition: state
    entity_id: switch.0x00158d0002112b1e
    state: 'off'
  action:
    - service: switch.turn_on
      entity_id: switch.0x00158d0002112b1e
    - service: timer.cancel
      entity_id: timer.hallway_light
    - service: timer.start
      entity_id: timer.hallway_light

- alias: "Turn off light in Hallway sw2"
  initial_state: true
  trigger:
    platform: state
    entity_id: switch.0x00158d0002113ace
    from: 'on'
    to: 'off'
  action:
    - service: switch.turn_off
      entity_id: switch.0x00158d0002112b1e
    - service: timer.cancel
      entity_id: timer.hallway_light

- alias: "Turn off light in Hallway"
  initial_state: true
  trigger:
    - platform: event
      event_type: timer.finished
      event_data:
        entity_id: timer.hallway_light
  condition:
    - condition: state
      entity_id: input_boolean.auto_turn_off_lights
      state: 'on'
    - condition: state
      entity_id: binary_sensor.0x00158d00032b7db7_contact
      state: 'off'
  action:
    service: switch.turn_off
    entity_id:
      - switch.0x00158d0002112b1e
      - switch.0x00158d0002113ace

- alias: "Hallway button is pressed and held"
  initial_state: true
  trigger:
    - platform: state
      entity_id: sensor.0x00158d0002e22617_action
      to: 'hold'
  action:
    - service: input_boolean.toggle
      entity_id: input_boolean.auto_turn_off_lights
    - service: homeassistant.toggle
      entity_id: switch.0x00158d0002112b1e
    - delay: '00:00:03'
    - service: homeassistant.toggle
      entity_id: switch.0x00158d0002112b1e

# Start HA
- alias: "Start Hallway timer if not starting"
  initial_state: true
  trigger:
    - platform: homeassistant
      event: start
  condition:
    - condition: state
      entity_id: switch.0x00158d0002112b1e
      state: 'on'
  action:
    - service: timer.start
      entity_id: timer.hallway_light

- alias: "Start Hallway sw3 timer 1"
  initial_state: true
  trigger:
    - platform: homeassistant
      event: start
  condition:
    - condition: state
      entity_id: switch.0x00158d00022a8150_right
      state: 'on'
  action:
    - service: timer.start
      entity_id: timer.hallway_light_sw3

- alias: "Start Hallway sw3 timer 2"
  initial_state: true
  trigger:
    - platform: state
      entity_id: switch.0x00158d00022a8150_right
      from: 'off'
      to: 'on'
  action:
    - service: timer.start
      entity_id: timer.hallway_light_sw3

- alias: "Turn off Hallway timer sw3"
  initial_state: true
  trigger:
    - platform: state
      entity_id: switch.0x00158d00022a8150_right
      to: 'off'
  action:
    - service: timer.cancel
      entity_id: timer.hallway_light_sw3

- alias: "Turn off light in Hallway sw3"
  initial_state: true
  trigger:
    - platform: event
      event_type: timer.finished
      event_data:
        entity_id: timer.hallway_light_sw3
  condition:
    - condition: state
      entity_id: input_boolean.auto_turn_off_lights
      state: 'on'
    - condition: state
      entity_id: switch.0x00158d00022a8150_right
      state: 'on'
  action:
    service: switch.turn_off
    entity_id:
      - switch.0x00158d00022a8150_right


