# Hallway
# Light
- alias: "Turn on lights in Hallway on conditions"
  initial_state: true
  trigger:
    platform: state
    entity_id: binary_sensor.door_window_sensor_158d00032b7db7
    to: 'on'
  condition:
    condition: state
    entity_id: switch.wall_switch_ln_158d0002112b1e
    state: 'off'
    for:
      minutes: 2
  action:
    - service: notify.telegram
      data:
        message: "\U0001F6AA The front door opened"
    - service: switch.turn_on
      entity_id:
        - switch.wall_switch_ln_158d0002112b1e
        - switch.wall_switch_ln_158d0001f9aaae
    - service: timer.cancel
      entity_id: timer.hallway_light
    - service: timer.start
      entity_id: timer.hallway_light

- alias: "Turn on light in Hallway sw1"
  initial_state: true
  trigger:
    platform: state
    entity_id: switch.wall_switch_ln_158d0002112b1e
    from: 'off'
    to: 'on'
  condition:
    condition: state
    entity_id: switch.wall_switch_ln_158d0001f9aaae
    state: 'off'
  action:
    - service: switch.turn_on
      entity_id: switch.wall_switch_ln_158d0001f9aaae
    - service: timer.cancel
      entity_id: timer.hallway_light
    - service: timer.start
      entity_id: timer.hallway_light

- alias: "Turn off light in Hallway sw1"
  initial_state: true
  trigger:
    platform: state
    entity_id: switch.wall_switch_ln_158d0002112b1e
    from: 'on'
    to: 'off'
  action:
    - service: switch.turn_off
      entity_id: switch.wall_switch_ln_158d0001f9aaae
    - service: timer.cancel
      entity_id: timer.hallway_light

- alias: "Turn on light in Hallway sw2"
  initial_state: true
  trigger:
    platform: state
    entity_id: switch.wall_switch_ln_158d0001f9aaae
    from: 'off'
    to: 'on'
  condition:
    condition: state
    entity_id: switch.wall_switch_ln_158d0002112b1e
    state: 'off'
  action:
    - service: switch.turn_on
      entity_id: switch.wall_switch_ln_158d0002112b1e
    - service: timer.cancel
      entity_id: timer.hallway_light
    - service: timer.start
      entity_id: timer.hallway_light

- alias: "Turn off light in Hallway sw2"
  initial_state: true
  trigger:
    platform: state
    entity_id: switch.wall_switch_ln_158d0001f9aaae
    from: 'on'
    to: 'off'
  action:
    - service: switch.turn_off
      entity_id: switch.wall_switch_ln_158d0002112b1e
    - service: timer.cancel
      entity_id: timer.hallway_light

- alias: "Turn off light in Hallway"
  initial_state: true
  trigger:
    - platform: event
      event_type: timer.finished
      event_data:
        entity_id: timer.hallway_light
  condition:
    - condition: state
      entity_id: input_boolean.auto_turn_off_lights
      state: 'on'
    - condition: state
      entity_id: binary_sensor.door_window_sensor_158d00032b7db7
      state: 'off'
  action:
    service: switch.turn_off
    entity_id:
      - switch.wall_switch_ln_158d0002112b1e
      - switch.wall_switch_ln_158d0001f9aaae

- alias: "Turn off light in hallway sw3"
  initial_state: true
  trigger:
    platform: time_pattern
    minutes: '/1'
  condition:
    - condition: state
      entity_id: input_boolean.auto_turn_off_lights
      state: 'on'
    - condition: state
      entity_id: switch.wall_switch_ln_right_158d00022a8150
      state: 'on'
      for:
        minutes: 5
  action:
    service: switch.turn_off
    entity_id: switch.wall_switch_ln_right_158d00022a8150

- alias: "Hallway button is pressed and held"
  initial_state: true
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.switch_158d0002e22617
      click_type: hold
  action:
    - service: input_boolean.toggle
      entity_id: input_boolean.auto_turn_off_lights

# Start HA
- alias: "Start Hallway timer if not starting"
  initial_state: true
  trigger:
    - platform: homeassistant
      event: start
  condition:
    - condition: state
      entity_id: switch.wall_switch_ln_158d0002112b1e
      state: 'on'
  action:
    - service: timer.start
      entity_id: timer.hallway_light

