# Hallway
# Light
- alias: "Turn on lights in Hallway on conditions"
  initial_state: true
  trigger:
    platform: state
    entity_id: binary_sensor.0x158d00032b7db7_contact
    to: 'on'
  condition:
    condition: state
    entity_id: switch.0x158d0002112b1e_switch
    state: 'off'
    for:
      minutes: 2
  action:
    - service: notify.telegram
      data:
        message: "\U0001F6AA The front door opened"
    - service: switch.turn_on
      entity_id:
        - switch.0x158d0002112b1e_switch
        - switch.0x158d0001f9aaae_switch
    - service: timer.cancel
      entity_id: timer.hallway_light
    - service: timer.start
      entity_id: timer.hallway_light

- alias: "Turn on light in Hallway sw1"
  initial_state: true
  trigger:
    platform: state
    entity_id: switch.0x158d0002112b1e_switch
    from: 'off'
    to: 'on'
  condition:
    condition: state
    entity_id: switch.0x158d0001f9aaae_switch
    state: 'off'
  action:
    - service: switch.turn_on
      entity_id: switch.0x158d0001f9aaae_switch
    - service: timer.cancel
      entity_id: timer.hallway_light
    - service: timer.start
      entity_id: timer.hallway_light

- alias: "Turn off light in Hallway sw1"
  initial_state: true
  trigger:
    platform: state
    entity_id: switch.0x158d0002112b1e_switch
    from: 'on'
    to: 'off'
  action:
    - service: switch.turn_off
      entity_id: switch.0x158d0001f9aaae_switch
    - service: timer.cancel
      entity_id: timer.hallway_light

- alias: "Turn on light in Hallway sw2"
  initial_state: true
  trigger:
    platform: state
    entity_id: switch.0x158d0001f9aaae_switch
    from: 'off'
    to: 'on'
  condition:
    condition: state
    entity_id: switch.0x158d0002112b1e_switch
    state: 'off'
  action:
    - service: switch.turn_on
      entity_id: switch.0x158d0002112b1e_switch
    - service: timer.cancel
      entity_id: timer.hallway_light
    - service: timer.start
      entity_id: timer.hallway_light

- alias: "Turn off light in Hallway sw2"
  initial_state: true
  trigger:
    platform: state
    entity_id: switch.0x158d0001f9aaae_switch
    from: 'on'
    to: 'off'
  action:
    - service: switch.turn_off
      entity_id: switch.0x158d0002112b1e_switch
    - service: timer.cancel
      entity_id: timer.hallway_light

- alias: "Turn off light in Hallway"
  initial_state: true
  trigger:
    - platform: event
      event_type: timer.finished
      event_data:
        entity_id: timer.hallway_light
  condition:
    - condition: state
      entity_id: input_boolean.auto_turn_off_lights
      state: 'on'
    - condition: state
      entity_id: binary_sensor.0x158d00032b7db7_contact
      state: 'off'
  action:
    service: switch.turn_off
    entity_id:
      - switch.0x158d0002112b1e_switch
      - switch.0x158d0001f9aaae_switch

- alias: "Turn off light in hallway sw3"
  initial_state: true
  trigger:
    platform: time_pattern
    minutes: '/1'
  condition:
    - condition: state
      entity_id: input_boolean.auto_turn_off_lights
      state: 'on'
    - condition: state
      entity_id: switch.0x158d00022a8150_channel_2
      state: 'on'
      for:
        minutes: 5
  action:
    service: switch.turn_off
    entity_id: switch.0x158d00022a8150_channel_2

- alias: "Hallway button is pressed and held"
  initial_state: true
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: sensor.0x158d0002e22617_action
      click_type: hold
  action:
    - service: input_boolean.toggle
      entity_id: input_boolean.auto_turn_off_lights

# Start HA
- alias: "Start Hallway timer if not starting"
  initial_state: true
  trigger:
    - platform: homeassistant
      event: start
  condition:
    - condition: state
      entity_id: switch.0x158d0002112b1e_switch
      state: 'on'
  action:
    - service: timer.start
      entity_id: timer.hallway_light

