# Kitchen
# Light
- alias: "Turn on light in Kitchen on conditions"
  initial_state: true
  trigger:
    - platform: state
      entity_id: binary_sensor.0x00158d00022515fe_occupancy
      from: 'off'
      to: 'on'
    - platform: state
      entity_id: sensor.0x54ef441000dbf5d6_movement
      to: 'movement'
    - platform: state
      entity_id: binary_sensor.0x54ef441000dbf5d6_presence
      to: 'Home'
  condition:
#   - condition: numeric_state
#     entity_id: sensor.0x00158d00022515fe_illuminance
#     below: 10
    - condition: state
      entity_id: switch.0x54ef441000d37ead
      state: 'off'
  action:
    - service: switch.turn_on
      entity_id: switch.0x54ef441000d37ead

- alias: "Turn on Kitchen timer"
  initial_state: true
  trigger:
    - platform: state
      entity_id: switch.0x54ef441000d37ead
      to: 'on'
    - platform: state
      entity_id: light.kitchen_lamp
      to: 'on'
  action:
    - service: timer.cancel
      entity_id: timer.kitchen_light
    - service: timer.start
      entity_id: timer.kitchen_light

- alias: "Reset Kitchen timer"
  initial_state: true
  trigger:
    - platform: state
      entity_id: binary_sensor.0x00158d00022515fe_occupancy
      from: 'off'
      to: 'on'
    - platform: state
      entity_id: sensor.0x54ef441000dbf5d6_movement
      to: 'movement'
    - platform: state
      entity_id: binary_sensor.0x54ef441000dbf5d6_presence
      to: 'Home'
  condition:
    - condition: state
      entity_id: switch.0x54ef441000d37ead
      state: 'on'
  action:
    - service: timer.cancel
      entity_id: timer.kitchen_light
    - service: timer.start
      entity_id: timer.kitchen_light

- alias: "Turn off light in Kitchen"
  initial_state: true
  trigger:
    - platform: event
      event_type: timer.finished
      event_data:
        entity_id: timer.kitchen_light
  condition:
    - condition: state
      entity_id: input_boolean.auto_turn_off_lights
      state: 'on'
  action:
    - service: switch.turn_off
      entity_id: switch.0x54ef441000d37ead
    - service: light.turn_off
      entity_id: light.kitchen_lamp

- alias: "Turn off Kitchen timer 1"
  initial_state: true
  trigger:
    - platform: state
      entity_id: switch.0x54ef441000d37ead
      to: 'off'
  condition:
    - condition: state
      entity_id: light.kitchen_lamp
      state: 'off'
  action:
    - service: timer.cancel
      entity_id: timer.kitchen_light

- alias: "Turn off Kitchen timer 2"
  initial_state: true
  trigger:
    - platform: state
      entity_id: light.kitchen_lamp
      to: 'off'
  condition:
    - condition: state
      entity_id: switch.0x54ef441000d37ead
      state: 'off'
  action:
    - service: timer.cancel
      entity_id: timer.kitchen_light

# Start HA
- alias: "Start Kitchen timer if not starting"
  initial_state: true
  trigger:
    - platform: homeassistant
      event: start
  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: switch.0x54ef441000d37ead
        state: 'on'
      - condition: state
        entity_id: light.kitchen_lamp
        state: 'on'
  action:
    - service: timer.start
      entity_id: timer.kitchen_light

# Reboot lamp if offline
#- alias: kitchen_lamp_offline
#  initial_state: true
#  trigger:
#    - platform: state
#      entity_id: light.kitchen_lamp
#      to: "unavailable"
#      for: "00:02:00"
#    - platform: state
#      entity_id: light.kitchen_lamp
#      to: "unavailable"
#      for: "00:05:00"
#    - platform: state
#      entity_id: light.kitchen_lamp
#      to: "unavailable"
#      for: "00:10:00"
#    - platform: state
#      entity_id: light.kitchen_lamp
#      to: "unavailable"
#      for: "00:15:00"
#  action:
#    - service: notify.telegram
#      data:
#        message: "Lamp in kitchen is offline, reboot it"
#    - service: switch.turn_off
#      entity_id: switch.shelly1_kitchen_lamp
#    - delay: '00:00:02'
#    - service: switch.turn_on
#      entity_id: switch.shelly1_kitchen_lamp

