# Kitchen
# Light
- alias: "Turn on light in Kitchen on conditions"
  initial_state: true
  id: turn_on_light_in_kitchen_on_conditions
  trigger:
    - platform: state
      entity_id: binary_sensor.0x00158d00022515fe_occupancy
      from: 'off'
      to: 'on'
    - platform: state
      entity_id: sensor.0x54ef441000dbf5d6_movement
      to: 'movement'
    - platform: state
      entity_id: binary_sensor.0x54ef441000dbf5d6_presence
      to: 'on'
    - platform: numeric_state
      entity_id: sensor.0x54ef441000dbf5d6_target_distance
      above: 0
  condition:
#   - condition: numeric_state
#     entity_id: sensor.0x00158d00022515fe_illuminance
#     below: 10
    - condition: state
      entity_id: switch.0x54ef441000d37ead
      state: 'off'
  action:
    - service: switch.turn_on
      entity_id: switch.0x54ef441000d37ead

- alias: "Turn on Kitchen timer"
  initial_state: true
  trigger:
    - platform: state
      entity_id: switch.0x54ef441000d37ead
      to: 'on'
    - platform: state
      entity_id: light.kitchen_lamp
      to: 'on'
  action:
    - service: timer.cancel
      entity_id: timer.kitchen_light
    - service: timer.start
      entity_id: timer.kitchen_light

- alias: "Reset Kitchen timer"
  initial_state: true
  id: reset_kitchen_timer
  trigger:
    - platform: state
      entity_id: binary_sensor.0x00158d00022515fe_occupancy
      from: 'off'
      to: 'on'
    - platform: state
      entity_id: sensor.0x54ef441000dbf5d6_movement
      to: 'movement'
    - platform: state
      entity_id: binary_sensor.0x54ef441000dbf5d6_presence
      to: 'on'
    - platform: numeric_state
      entity_id: sensor.0x54ef441000dbf5d6_target_distance
      above: 0.1
  condition:
    - condition: state
      entity_id: switch.0x54ef441000d37ead
      state: 'on'
  action:
    - service: timer.cancel
      entity_id: timer.kitchen_light
    - service: timer.start
      entity_id: timer.kitchen_light

- alias: "Turn off light in Kitchen"
  initial_state: true
  trigger:
    - platform: event
      event_type: timer.finished
      event_data:
        entity_id: timer.kitchen_light
  condition:
    - condition: state
      entity_id: input_boolean.auto_turn_off_lights
      state: 'on'
  action:
    - service: switch.turn_off
      entity_id: switch.0x54ef441000d37ead
    - service: light.turn_off
      entity_id: light.kitchen_lamp

- alias: "Turn off Kitchen timer 1"
  initial_state: true
  trigger:
    - platform: state
      entity_id: switch.0x54ef441000d37ead
      to: 'off'
  condition:
    - condition: state
      entity_id: light.kitchen_lamp
      state: 'off'
  action:
    - service: timer.cancel
      entity_id: timer.kitchen_light

- alias: "Turn off Kitchen timer 2"
  initial_state: true
  trigger:
    - platform: state
      entity_id: light.kitchen_lamp
      to: 'off'
  condition:
    - condition: state
      entity_id: switch.0x54ef441000d37ead
      state: 'off'
  action:
    - service: timer.cancel
      entity_id: timer.kitchen_light

# Start HA
- alias: "Start Kitchen timer if not starting"
  initial_state: true
  trigger:
    - platform: homeassistant
      event: start
  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: switch.0x54ef441000d37ead
        state: 'on'
      - condition: state
        entity_id: light.kitchen_lamp
        state: 'on'
  action:
    - service: timer.start
      entity_id: timer.kitchen_light
