# Kitchen
# Light
- alias: "Turn on light in Kitchen on conditions"
  initial_state: true
  trigger:
    - platform: state
      entity_id: binary_sensor.0x158d00022515fe_motion
      from: 'off'
      to: 'on'
#   - platform: state
#     entity_id: binary_sensor.582d3460a918_motion
#     from: 'off'
#     to: 'on'
  condition:
#   - condition: numeric_state
#     entity_id: sensor.0x158d00022515fe_illuminance
#     below: 10
    - condition: state
      entity_id: switch.0x158d000211434a_switch
      state: 'off'
  action:
    - service: switch.turn_on
      entity_id: switch.0x158d000211434a_switch

- alias: "Turn on Kitchen timer"
  initial_state: true
  trigger:
    - platform: state
      entity_id: switch.0x158d000211434a_switch
      to: 'on'
    - platform: state
      entity_id: light.kitchen_lamp
      to: 'on'
  action:
    - service: timer.cancel
      entity_id: timer.kitchen_light
    - service: timer.start
      entity_id: timer.kitchen_light

- alias: "Reset Kitchen timer"
  initial_state: true
  trigger:
    - platform: event
      event_type: xiaomi_aqara.motion
      event_data:
        entity_id: binary_sensor.0x158d00022515fe_motion
#   - platform: event
#     event_type: xiaomi_aqara.motion
#     event_data:
#       entity_id: binary_sensor.582d3460a918_motion
  condition:
    - condition: state
      entity_id: switch.0x158d000211434a_switch
      state: 'on'
  action:
    - service: timer.cancel
      entity_id: timer.kitchen_light
    - service: timer.start
      entity_id: timer.kitchen_light

- alias: "Turn off light in Kitchen"
  initial_state: true
  trigger:
    - platform: event
      event_type: timer.finished
      event_data:
        entity_id: timer.kitchen_light
  condition:
    - condition: state
      entity_id: input_boolean.auto_turn_off_lights
      state: 'on'
  action:
    - service: switch.turn_off
      entity_id: switch.0x158d000211434a_switch
    - service: light.turn_off
      entity_id: light.kitchen_lamp

- alias: "Turn off Kitchen timer 1"
  initial_state: true
  trigger:
    - platform: state
      entity_id: switch.0x158d000211434a_switch
      to: 'off'
  condition:
    - condition: state
      entity_id: light.kitchen_lamp
      state: 'off'
  action:
    - service: timer.cancel
      entity_id: timer.kitchen_light

- alias: "Turn off Kitchen timer 2"
  initial_state: true
  trigger:
    - platform: state
      entity_id: light.kitchen_lamp
      to: 'off'
  condition:
    - condition: state
      entity_id: switch.0x158d000211434a_switch
      state: 'off'
  action:
    - service: timer.cancel
      entity_id: timer.kitchen_light

# Start HA
- alias: "Start Kitchen timer if not starting"
  initial_state: true
  trigger:
    - platform: homeassistant
      event: start
  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: switch.0x158d000211434a_switch
        state: 'on'
      - condition: state
        entity_id: light.kitchen_lamp
        state: 'on'
  action:
    - service: timer.start
      entity_id: timer.kitchen_light

