- alias: "Set brightness for lamp in living room"
  initial_state: false
  trigger:
    platform: state
    entity_id: light.living_room_lamp
    from: 'off'
    to: 'on'
  action:
    - service: yeelight.set_mode
      data:
        entity_id: light.living_room_lamp
        mode: normal
    - service: yeelight.set_color_temp_scene
      data:
        entity_id: light.living_room_lamp
        brightness: 75
        kelvin: 3000

- alias: "Livingroom switch left"
  initial_state: true
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.wall_switch_left_158d0002afc3c7
      click_type: single
  action:
    service: light.toggle
    entity_id:
      - group.living_room_spot_left

- alias: "Livingroom switch right"
  initial_state: true
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.wall_switch_right_158d0002afc3c7
      click_type: single
  action:
    service: light.toggle
    entity_id:
      - group.living_room_spot_right

- alias: "Livingroom switch left long"
  initial_state: true
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.wall_switch_left_158d0002afc3c7
      click_type: long
  action:
    service: light.turn_off
    entity_id:
      - group.living_room_spot_left

- alias: "Livingroom switch right long"
  initial_state: true
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.wall_switch_right_158d0002afc3c7
      click_type: long
  action:
    service: light.turn_off
    entity_id:
      - group.living_room_spot_right

- alias: "Livingroom switch both"
  initial_state: true
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.wall_switch_both_158d0002afc3c7
      click_type: both
  action:
    service: light.toggle
    entity_id:
      - group.living_room_spot_right
      - group.living_room_spot_left

- alias: "Livingroom switch both long"
  initial_state: true
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.wall_switch_both_158d0002afc3c7
      click_type: long_both
  action:
    service: light.turn_off
    entity_id:
      - group.living_room_spot_right
      - group.living_room_spot_left

