- alias: "Livingroom switch left"
  initial_state: true
  trigger:
    - platform: state
      entity_id: sensor.0x00158d0002afc3c7_action
      to: 'single_left'
  action:
    service: light.toggle
    entity_id:
      - group.living_room_spot_left

- alias: "Livingroom switch right"
  initial_state: true
  trigger:
    - platform: state
      entity_id: sensor.0x00158d0002afc3c7_action
      to: 'single_right'
  action:
    service: light.toggle
    entity_id:
      - group.living_room_spot_right

- alias: "Livingroom switch left long"
  initial_state: true
  trigger:
    - platform: state
      entity_id: sensor.0x00158d0002afc3c7_action
      to: 'hold_left'
  action:
    service: light.turn_off
    entity_id:
      - group.living_room_spot_left

- alias: "Livingroom switch right long"
  initial_state: true
  trigger:
    - platform: state
      entity_id: sensor.0x00158d0002afc3c7_action
      to: 'hold_right'
  action:
    service: light.turn_off
    entity_id:
      - group.living_room_spot_right

- alias: "Livingroom switch both"
  initial_state: true
  trigger:
    - platform: state
      entity_id: sensor.0x00158d0002afc3c7_action
      to: 'single_both'
  action:
    service: light.toggle
    entity_id:
      - group.living_room_spot_right
      - group.living_room_spot_left

- alias: "Livingroom switch both long"
  initial_state: true
  trigger:
    - platform: state
      entity_id: sensor.0x00158d0002afc3c7_action
      to: 'hold_both'
  action:
    service: light.turn_off
    entity_id:
      - group.living_room_spot_right
      - group.living_room_spot_left

