- alias: "Livingroom switch left"
  initial_state: true
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: sensor.0x158d0002afc3c7_action
      click_type: button_1_single
  action:
    service: light.toggle
    entity_id:
      - group.living_room_spot_left

- alias: "Livingroom switch right"
  initial_state: true
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: sensor.0x158d0002afc3c7_action
      click_type: button_2_single
  action:
    service: light.toggle
    entity_id:
      - group.living_room_spot_right

- alias: "Livingroom switch left long"
  initial_state: true
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: sensor.0x158d0002afc3c7_action
      click_type: button_1_hold
  action:
    service: light.turn_off
    entity_id:
      - group.living_room_spot_left

- alias: "Livingroom switch right long"
  initial_state: true
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: sensor.0x158d0002afc3c7_action
      click_type: button_2_hold
  action:
    service: light.turn_off
    entity_id:
      - group.living_room_spot_right

- alias: "Livingroom switch both"
  initial_state: true
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: sensor.0x158d0002afc3c7_action
      click_type: button_both_single
  action:
    service: light.toggle
    entity_id:
      - group.living_room_spot_right
      - group.living_room_spot_left

- alias: "Livingroom switch both long"
  initial_state: true
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: sensor.0x158d0002afc3c7_action
      click_type: button_both_hold
  action:
    service: light.turn_off
    entity_id:
      - group.living_room_spot_right
      - group.living_room_spot_left

