- alias: "Turn on bedside lamp"
  initial_state: true
  trigger:
    platform: numeric_state
    entity_id: sun.sun
    value_template: "{{ state.attributes.elevation }}"
    below: 7
    above: 5
  condition:
    - condition: state
      state: 'off'
      entity_id: light.bedside
    - condition: time
      after: '15:00:00'
      before: '22:00:00'
  action:
    service: light.turn_on
    entity_id: light.bedside
    data:
      brightness_pct: 60
      kelvin: 6500

- alias: "Turn off bedside lamp"
  initial_state: true
  trigger:
    platform: time
    at: '02:00:00'
  condition:
    condition: state
    entity_id: light.bedside
    state: 'on'
  action:
    service: light.turn_off
    entity_id: light.bedside

- alias: "Bedroom1 button is pressed single"
  initial_state: true
  trigger:
    - platform: state
      entity_id: sensor.0x00158d0001a66df0_action
      to: 'single'
  action:
    - service: light.turn_off
      entity_id:
        - light.kitchen_lamp
        - group.living_room_spot_right
        - group.living_room_spot_left
        - light.living_room_lamp
        - light.balcony_strip
        - light.master_bedroom_lamp
    - service: switch.turn_off
      entity_id:
        - switch.0x54ef441000d37ead

- alias: "Bedroom1 button is pressed double"
  initial_state: true
  trigger:
    - platform: state
      entity_id: sensor.0x00158d0001a66df0_action
      to: 'double'
  action:
    - service: light.turn_on
      entity_id:
        - light.living_room_lamp
        - light.balcony_strip
        - light.master_bedroom_lamp
    - service: switch.turn_on
      entity_id:
        - switch.0x54ef441000d37ead
