- alias: "Plant Data Update"
  initial_state: 'on'
  trigger:
    - platform: numeric_state
      entity_id:
        - sensor.mf1_moisture
        - sensor.mf2_moisture
        - sensor.mf3_moisture
      below: 30
  action:
    - service: notify.telegram
      data:
        message: "\U0001F940 This flower needs water - '{{ trigger.from_state.attributes.friendly_name }}', влажность {{ trigger.from_state.state }}"
