- alias: "Plant Data Update"
  initial_state: true
  trigger:
    - platform: numeric_state
      entity_id:
        - sensor.mf1_moisture
        - sensor.mf2_moisture
#       - sensor.mf3_moisture
      below: 25
  action:
    - service: notify.telegram
      data:
        message: "\U0001F940 This flower needs water - '{{ trigger.from_state.attributes.friendly_name }}', moisture {{ trigger.to_state.state }}"
