- alias: "Door opened in storeroom"
  initial_state: true
  trigger:
    platform: state
    entity_id: binary_sensor.0x158d0002537042_contact
    to: 'on'
  condition:
    condition: state
    entity_id: switch.0x158d0002235125_switch
    state: 'off'
  action:
    service: switch.turn_on
    entity_id: switch.0x158d0002235125_switch

- alias: "Door closed in storeroom"
  initial_state: true
  trigger:
    platform: state
    entity_id: binary_sensor.0x158d0002537042_contact
    to: 'off'
  condition:
    condition: state
    entity_id: switch.0x158d0002235125_switch
    state: 'on'
  action:
    service: switch.turn_off
    entity_id: switch.0x158d0002235125_switch

