# System start
#- alias: system_start
#  initial_state: true
#  trigger:
#    platform: homeassistant
#    event: start
#  action:
#    - service: counter.increment
#      entity_id: counter.restart_counter

# Errors counter
#- alias: system_error_counter
#  initial_state: true
#  mode: queued
#  trigger:
#    platform: event
#    event_type: system_log_event
#    event_data:
#      level: ERROR
#  action:
#    - service: counter.increment
#      entity_id: counter.error_counter

# Warning counter
#- alias: system_warning_counter
#  initial_state: true
#  mode: queued
#  trigger:
#    platform: event
#    event_type: system_log_event
#    event_data:
#      level: WARNING
#  action:
#    service: counter.increment
#    entity_id: counter.warning_counter

#- alias: reset_system_counters
#  initial_state: true
#  trigger:
#    - platform: time
#      at: '00:00:02'
#  action:
#    - service: counter.reset
##     entity_id: counter.warning_counter, counter.error_counter, counter.restart_counter
#      entity_id: counter.restart_counter

- alias: system_entity_change
  initial_state: true
  mode: parallel
  trigger:
    - platform: event
      event_type: entity_registry_updated
  condition:
    - condition: template
      value_template: "{{ trigger.event.data.action != 'update' }}"
  action:
    - service: notify.telegram
      data:
        message: "\U00002747 {{ trigger.event.data.action | capitalize }}: {{ trigger.event.data.old_entity_id+'->' if trigger.event.data.old_entity_id is defined }}{{ trigger.event.data.entity_id if trigger.event.data.entity_id is defined else 'NA' }}"

