- alias: system_entity_change
  initial_state: true
  mode: queued
  trigger:
    - platform: event
      event_type: entity_registry_updated
  action:
    - service: notify.telegram
      data:
        message: "\U00002747 {{ trigger.event.data.action | capitalize }}: {{ trigger.event.data.old_entity_id+'->' if trigger.event.data.old_entity_id is defined }}{{ trigger.event.data.entity_id if trigger.event.data.entity_id is defined else 'NA' }}"


- alias: system_database_purge
  initial_state: true
  trigger:
    - platform: time
      at: '03:00:00'
  action:
    - service: recorder.purge
      data:
        keep_days: 3
        repack: true

- alias: notify unavailable entities
  initial_state: true
  trigger:
    - platform: numeric_state
      entity_id: sensor.total_entities_unavail
      above: 10
      for:
        minutes: 5
  action:
    - service: notify.telegram
      data:
        message: "\U00002620 {{ states('sensor.total_entities_unavail') }} entities are unavailable"

- alias: Good morning
  initial_state: true
  trigger:
    - platform: time
      at: '08:01:00'
  action:
    - service: notify.telegram
      data:
        message: |
          <pre>
          {{"\U0001F305" }} Good morning!
          Hallway:     {{ states('sensor.temperature_158d000231f03e') }}°C
          Kitchen:     {{ states('sensor.temperature_158d0002ca0395') }}°C
          Living Room: {{ states('sensor.temperature_158d0002bfe958') }}°C
          Bedroom1:    {{ states('sensor.temperature_158d0002323856') }}°C
          Bedroom2:    {{ states('sensor.temperature_158d000231f03e') }}°C
          Bathroom:    {{ states('sensor.temperature_158d0001ab2a27') }}°C
          Balcony:     {{ states('sensor.temperature_158d00027300cc') }}°C
          Outdoor:     {{ states('sensor.nodemcu_3_outdoor_temperature') }}°C
          Fazenda:     {{ states('sensor.fazenda_outdoor_temperature') }}°C
          Weather:     {{ states('sensor.openweathermap_forecast_temperature_low') }} - {{ states('sensor.openweathermap_forecast_temperature') }}°C, {{ states('sensor.openweathermap_forecast_condition') }}
          {{ states('sensor.total_entities_unavail') }} entities are unavailable
          </pre>

