# System start
- alias: system_start
  initial_state: 'on'
  trigger:
    platform: homeassistant
    event: start
  action:
    - service: counter.increment
      entity_id: counter.restart_counter

# Errors counter
- alias: system_error_counter
  initial_state: 'on'
  mode: queued
  trigger:
    platform: event
    event_type: system_log_event
    event_data:
      level: ERROR
  action:
    - service: counter.increment
      entity_id: counter.error_counter

# Warning counter
- alias: system_warning_counter
  initial_state: 'on'
  mode: queued
  trigger:
    platform: event
    event_type: system_log_event
    event_data:
      level: WARNING
  action:
    service: counter.increment
    entity_id: counter.warning_counter

- alias: reset_system_counters
  initial_state: 'on'
  trigger:
    - platform: time
      at: '00:00:02'
  action:
    - service: counter.reset
#     entity_id: counter.warning_counter, counter.error_counter, counter.restart_counter
      entity_id: counter.restart_counter

# ##################################
# System - Entity Change
# ##################################
- alias: system_entity_change
  initial_state: 'on'
  mode: parallel
  trigger:
    - platform: event
      event_type: entity_registry_updated
  action:
    - service: notify.telegram
      data_template:
        message: "\U00002747 {{ trigger.event.data.action | capitalize }}: {{ trigger.event.data.old_entity_id+'->' if trigger.event.data.old_entity_id is defined }}{{ trigger.event.data.entity_id if trigger.event.data.entity_id is defined else 'NA' }}"

