- alias: system_entity_change
  initial_state: true
  mode: queued
  trigger:
    - platform: event
      event_type: entity_registry_updated
  action:
    - service: notify.telegram
      data:
        message: "\U00002747 {{ trigger.event.data.action | capitalize }}: {{ trigger.event.data.old_entity_id+'->' if trigger.event.data.old_entity_id is defined }}{{ trigger.event.data.entity_id if trigger.event.data.entity_id is defined else 'NA' }}"


- alias: system_database_purge
  initial_state: true
  trigger:
    - platform: time
      at: '03:00:00'
  action:
    - service: recorder.purge
      data:
        keep_days: 3
        repack: true

- alias: notify unavailable entities
  initial_state: true
  trigger:
    - platform: numeric_state
      entity_id: sensor.total_entities_unavail
      above: 10
      for:
        minutes: 5
  action:
    - service: notify.telegram
      data:
        message: "\U00002620 {{ states('sensor.total_entities_unavail') }} entities are unavailable"
