- alias: system_entity_change
  initial_state: true
  mode: parallel
  trigger:
    - platform: event
      event_type: entity_registry_updated
  condition:
    - condition: template
      value_template: "{{ trigger.event.data.action != 'update' }}"
  action:
    - service: notify.telegram
      data:
        message: "\U00002747 {{ trigger.event.data.action | capitalize }}: {{ trigger.event.data.old_entity_id+'->' if trigger.event.data.old_entity_id is defined }}{{ trigger.event.data.entity_id if trigger.event.data.entity_id is defined else 'NA' }}"

