#- alias: "HACS Persistent Notification"
#  initial_state: true
#  trigger:
#    platform: numeric_state
#    entity_id: sensor.hacs
#    above: 0
#  action:
#   - service: persistent_notification.create
#     data:
#        title: "HACS updates are available"
#        message: >
#          {% for item in states.sensor.hacs.attributes.repositories %}
#            {{ item.display_name }} {{ item.installed_version }} -> {{ item.available_version }}
#          {% endfor %}

- alias: "HA Persistent Notification"
  initial_state: true
  trigger:
    - platform: state
      entity_id: binary_sensor.update_available
      to: 'on'
  action:
    - service: persistent_notification.create
      data:
        title: "HA Upgrade is Available"
        message: "Upgrade from {{ states('sensor.ha_current') }} to {{ states('sensor.ha_latest') }} is available"
