- alias: "Water leakage"
  initial_state: true
  trigger:
    platform: state
    entity_id:
      - binary_sensor.0x00158d000232989c_water_leak
      - binary_sensor.0x00158d000233ddf2_water_leak
      - binary_sensor.0x00158d00023aa420_water_leak
    to: 'on'
  action:
    - service: xiaomi_aqara.play_ringtone
      data:
        gw_mac: !secret xgate_1_mac
        ringtone_id: 0
        ringtone_vol: 80
    - service: notify.telegram
      data:
        message: "\U0001F4A6 {{ trigger.from_state.attributes.friendly_name }}age !!!"

- alias: "Water leakage fixed"
  initial_state: true
  trigger:
    platform: state
    entity_id:
      - binary_sensor.0x00158d000232989c_water_leak
      - binary_sensor.0x00158d000233ddf2_water_leak
      - binary_sensor.0x00158d00023aa420_water_leak
    from: 'on'
    to: 'off'
  action:
    - service: xiaomi_aqara.stop_ringtone
      data:
        gw_mac: !secret xgate_1_mac
    - service: xiaomi_aqara.stop_ringtone
      data:
        gw_mac: !secret xgate_2_mac
    - service: notify.telegram
      data:
        message: "\U00002705 {{ trigger.from_state.attributes.friendly_name }}age fixed"

