- alias: "Water leakage"
  initial_state: 'on'
  trigger:
    platform: state
    entity_id:
      - binary_sensor.water_leak_sensor_158d000232989c
      - binary_sensor.water_leak_sensor_158d000233ddf2
      - binary_sensor.water_leak_sensor_158d00023aa420
    to: 'on'
  action:
    - service: xiaomi_aqara.play_ringtone
      data:
        gw_mac: !secret xgate_1_mac
        ringtone_id: 0
        ringtone_vol: 80
    - service: xiaomi_aqara.play_ringtone
      data:
        gw_mac: !secret xgate_2_mac
        ringtone_id: 0
        ringtone_vol: 80
    - service: notify.telegram
      data_template:
        message: "\U0001F4A6 {{ trigger.from_state.attributes.friendly_name }}age !!!"

- alias: "Water leakage fixed"
  initial_state: 'on'
  trigger:
    platform: state
    entity_id:
      - binary_sensor.water_leak_sensor_158d000232989c
      - binary_sensor.water_leak_sensor_158d000233ddf2
      - binary_sensor.water_leak_sensor_158d00023aa420
    from: 'on'
    to: 'off'
  action:
    - service: xiaomi_aqara.stop_ringtone
      data:
        gw_mac: !secret xgate_1_mac
    - service: xiaomi_aqara.stop_ringtone
      data:
        gw_mac: !secret xgate_2_mac
    - service: notify.telegram
      data_template:
        message: "\U00002705 {{ trigger.from_state.attributes.friendly_name }}age fixed"

