- alias: "Water leakage"
  initial_state: true
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.0x54ef441000e32a3f_water_leak
        - binary_sensor.0x54ef441000e32cab_water_leak
        - binary_sensor.0x54ef441000e32bdf_water_leak
      to: 'on'
  action:
    - service: xiaomi_aqara.play_ringtone
      data:
        gw_mac: !secret xgate_1_mac
        ringtone_id: 0
        ringtone_vol: 80
    - service: notify.send_message
      data:
        entity_id: notify.telegram_vtel
        message: "\U0001F4A6 {{ state_attr(trigger.entity_id, 'friendly_name') if trigger.entity_id is defined else 'Test' }} - Water leakage detected!!!"

- alias: "Water leakage fixed"
  initial_state: true
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.0x54ef441000e32a3f_water_leak
        - binary_sensor.0x54ef441000e32cab_water_leak
        - binary_sensor.0x54ef441000e32bdf_water_leak
      from: 'on'
      to: 'off'
  action:
    - service: notify.send_message
      data:
        entity_id: notify.telegram_vtel
        message: "\U00002705 {{ state_attr(trigger.entity_id, 'friendly_name') if trigger.entity_id is defined else 'Test' }} - Water leakage fixed"
    - service: xiaomi_aqara.stop_ringtone
      data:
        gw_mac: !secret xgate_1_mac
    - service: xiaomi_aqara.stop_ringtone
      data:
        gw_mac: !secret xgate_2_mac

