# WC
# Light
- alias: "Turn on light in WC on conditions"
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: binary_sensor.door_window_sensor_158d00024de627
      to: 'on'
    - platform: event
      event_type: xiaomi_aqara.motion
      event_data:
        entity_id: binary_sensor.motion_sensor_158d0004466f8f
  condition:
    - condition: state
      entity_id: switch.wall_switch_ln_158d00022360fe
      state: 'off'
  action:
    - service: switch.turn_on
      entity_id: switch.wall_switch_ln_158d00022360fe
    - service: timer.cancel
      entity_id: timer.wc_light
    - service: timer.start
      entity_id: timer.wc_light

- alias: "Turn on WC timer"
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: switch.wall_switch_ln_158d00022360fe
      to: 'on'
  action:
    - service: timer.cancel
      entity_id: timer.wc_light
    - service: timer.start
      entity_id: timer.wc_light

- alias: "Reset WC timer on conditions"
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: binary_sensor.door_window_sensor_158d00024de627
      to: 'off'
    - platform: event
      event_type: xiaomi_aqara.motion
      event_data:
        entity_id: binary_sensor.motion_sensor_158d0004466f8f
  condition:
    - condition: state
      entity_id: switch.wall_switch_ln_158d00022360fe
      state: 'on'
  action:
    - service: timer.cancel
      entity_id: timer.wc_light
    - service: timer.start
      entity_id: timer.wc_light

- alias: "Turn off light in WC on conditions"
  initial_state: 'on'
  trigger:
    - platform: event
      event_type: timer.finished
      event_data:
        entity_id: timer.wc_light
  condition:
    - condition: state
      entity_id: input_boolean.auto_turn_off_lights
      state: 'on'
    - condition: state
      entity_id: switch.wall_switch_ln_158d00022360fe
      state: 'on'
    - condition: state
      entity_id: binary_sensor.door_window_sensor_158d00024de627
      state: 'off'
  action:
    - service: switch.turn_off
      entity_id: switch.wall_switch_ln_158d00022360fe

- alias: "Turn off wc timer if light is off"
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: switch.wall_switch_ln_158d00022360fe
      to: 'off'
  action:
    - service: timer.cancel
      entity_id: timer.wc_light

# FAN
- alias: "Turn off WC fan"
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: switch.sonoff_wc_relay
      to: 'off'
    - platform: event
      event_type: timer.finished
      event_data:
        entity_id: timer.wc_fan
  action:
    - service: switch.turn_off
      entity_id: switch.sonoff_wc_relay
    - service: timer.cancel
      entity_id: timer.wc_fan

- alias: "Turn on WC fan"
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: switch.sonoff_wc_relay
      to: 'on'
  action:
    - service: timer.cancel
      entity_id: timer.wc_fan
    - service: timer.start
      entity_id: timer.wc_fan

- alias: "Turn on WC fan on schedule"
  initial_state: 'on'
  trigger:
    - platform: time
      at: '07:45'
    - platform: time
      at: '13:00'
    - platform: time
      at: '18:00'
  condition:
    - condition: state
      entity_id: input_boolean.auto_fan
      state: 'on'
  action:
    - service: switch.turn_on
      entity_id: switch.sonoff_wc_relay
    - service: timer.cancel
      entity_id: timer.wc_fan
    - service: timer.start
      entity_id: timer.wc_fan
      data_template:
        duration: 00:05:00

# Start HA
- alias: "Start WC timer if not starting"
  initial_state: 'on'
  trigger:
    - platform: homeassistant
      event: start
  condition:
    - condition: state
      entity_id: switch.wall_switch_ln_158d00022360fe
      state: 'on'
  action:
    - service: timer.start
      entity_id: timer.wc_light

- alias: "Start WC fan timer if not starting"
  initial_state: 'on'
  trigger:
    - platform: homeassistant
      event: start
  condition:
    - condition: state
      entity_id: switch.sonoff_wc_relay
      state: 'on'
  action:
    - service: timer.start
      entity_id: timer.wc_fan

