# WC
# Light
- alias: "Toggle light in WC"
  initial_state: true
  trigger:
    - platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: sensor.0x158d00022360fe_action
        click_type: single
  action:
    - service: light.toggle
      entity_id: group.wc_spots

- alias: "Turn on light in WC on conditions"
  initial_state: true
  trigger:
    - platform: state
      entity_id: binary_sensor.door_window_sensor_158d00024de627
      to: 'on'
    - platform: event
      event_type: xiaomi_aqara.motion
      event_data:
        entity_id: binary_sensor.motion_sensor_158d0004466f8f
  condition:
    - condition: state
      entity_id: group.wc_spots
      state: 'off'
  action:
    - service: light.turn_on
      entity_id: group.wc_spots

- alias: "Turn on WC timer"
  initial_state: true
  trigger:
    - platform: state
      entity_id: group.wc_spots
      to: 'on'
  action:
    - service: timer.cancel
      entity_id: timer.wc_light
    - service: timer.start
      entity_id: timer.wc_light

- alias: "Reset WC timer on conditions"
  initial_state: true
  trigger:
    - platform: state
      entity_id: binary_sensor.door_window_sensor_158d00024de627
      to: 'off'
    - platform: event
      event_type: xiaomi_aqara.motion
      event_data:
        entity_id: binary_sensor.motion_sensor_158d0004466f8f
  condition:
    - condition: state
      entity_id: group.wc_spots
      state: 'on'
  action:
    - service: timer.cancel
      entity_id: timer.wc_light
    - service: timer.start
      entity_id: timer.wc_light

- alias: "Turn off light in WC on conditions"
  initial_state: true
  trigger:
    - platform: event
      event_type: timer.finished
      event_data:
        entity_id: timer.wc_light
  condition:
    - condition: state
      entity_id: input_boolean.auto_turn_off_lights
      state: 'on'
    - condition: state
      entity_id: group.wc_spots
      state: 'on'
    - condition: state
      entity_id: binary_sensor.door_window_sensor_158d00024de627
      state: 'off'
  action:
    - service: light.turn_off
      entity_id: group.wc_spots

- alias: "Turn off wc timer if light is off"
  initial_state: true
  trigger:
    - platform: state
      entity_id: group.wc_spots
      to: 'off'
  action:
    - service: timer.cancel
      entity_id: timer.wc_light

# FAN
- alias: "Turn off WC fan"
  initial_state: true
  trigger:
    - platform: state
      entity_id: switch.sonoff_wc_relay
      to: 'off'
    - platform: event
      event_type: timer.finished
      event_data:
        entity_id: timer.wc_fan
  action:
    - service: switch.turn_off
      entity_id: switch.sonoff_wc_relay
    - service: timer.cancel
      entity_id: timer.wc_fan

- alias: "Turn on WC fan"
  initial_state: true
  trigger:
    - platform: state
      entity_id: switch.sonoff_wc_relay
      to: 'on'
  action:
    - service: timer.cancel
      entity_id: timer.wc_fan
    - service: timer.start
      entity_id: timer.wc_fan

- alias: "Turn on WC fan on schedule"
  initial_state: true
  trigger:
    - platform: time
      at:
        - '07:45'
        - '13:00'
        - '18:00'
  condition:
    - condition: state
      entity_id: input_boolean.auto_fan
      state: 'on'
  action:
    - service: switch.turn_on
      entity_id: switch.sonoff_wc_relay
    - service: timer.cancel
      entity_id: timer.wc_fan
    - service: timer.start
      entity_id: timer.wc_fan
      data:
        duration: 00:05:00

# Start HA
- alias: "Start WC timer if not starting"
  initial_state: true
  trigger:
    - platform: homeassistant
      event: start
  condition:
    - condition: state
      entity_id: group.wc_spots
      state: 'on'
  action:
    - service: timer.start
      entity_id: timer.wc_light

- alias: "Start WC fan timer if not starting"
  initial_state: true
  trigger:
    - platform: homeassistant
      event: start
  condition:
    - condition: state
      entity_id: switch.sonoff_wc_relay
      state: 'on'
  action:
    - service: timer.start
      entity_id: timer.wc_fan

