################################################################################

input_boolean:
  ups_on_battery:
    name: UPS on battery (memory)
    icon: mdi:car-battery

input_number:
  power_outage_timestamp:
    name: "Power Outage Timestamp"
    min: 0
    max: 9999999999
    step: 1
    mode: box

template:
  - trigger:
      - platform: time_pattern
        minutes: "/1"
      - platform: state
        entity_id: input_number.power_outage_timestamp
    sensor:
      - name: "Power Outage Start Time"
        unique_id: power_outage_start_time
        state: >
          {% set timestamp = states('input_number.power_outage_timestamp') | float(0) %}
          {% if timestamp > 0 %}
            {{ timestamp | timestamp_local }}
          {% else %}
            unavailable
          {% endif %}
        device_class: timestamp
        icon: mdi:power-plug-off

      - name: "Power Outage Duration Formatted"
        unique_id: power_outage_duration_formatted
        state: >
          {% set timestamp = states('input_number.power_outage_timestamp') | float(0) %}
          {% if timestamp > 0 %}
            {% set duration = (now().timestamp() - timestamp) | int %}
            {% set hours = duration // 3600 %}
            {% set minutes = (duration % 3600) // 60 %}
            {{ '%02d:%02d' | format(hours, minutes) }}
          {% else %}
            -
          {% endif %}
        icon: mdi:timer-outline

  - binary_sensor:
      - name: "Mains Power Status"
        unique_id: mains_power_status
        state: >
          {{ states('input_number.power_outage_timestamp') | float(0) == 0 }}
        device_class: power
        icon: >
          {% if states('input_number.power_outage_timestamp') | float(0) == 0 %}
            mdi:power-plug
          {% else %}
            mdi:power-plug-off
          {% endif %}

automation:
  - alias: 'Notify when UPS goes on battery'
    initial_state: true
    trigger:
      - platform: state
        entity_id: sensor.ups_status_data
    condition:
      - condition: template
        value_template: >
          {{ trigger.from_state is not none and trigger.to_state is not none
             and 'OL' in trigger.from_state.state and 'OB' in trigger.to_state.state }}
    action:
      - delay: '00:02:00'
      - service: notify.send_message
        data:
          entity_id: notify.telegram_vtel
          message: >
            ⚠ {{ now().strftime('%Y-%m-%d %H:%M') }}
            | 2 Mains voltage (UPS) is missing
            | ip: {{ states('sensor.myip') }}

  - alias: 'Notify when working PowerStation'
    initial_state: true
    trigger:
      - platform: numeric_state
        entity_id: sensor.0xa46dd4fffe4f985d_power
        below: 1
        id: power_lost
      - platform: homeassistant
        event: start
        id: ha_start
    action:
      # TEST: delay 2 min after ha_start to let entities restore their states
      - if:
          - condition: trigger
            id: ha_start
        then:
          - delay: "00:02:00"
      - condition: template
        value_template: >
          {{ states('sensor.0xa46dd4fffe4f985d_power') | float(999) < 1
             and states('input_number.power_outage_timestamp') | float(0) == 0 }}
      - service: light.turn_on
        entity_id: light.gateway_light_7811dcb245b2
        data:
          brightness: 127
          rgb_color: [255, 0, 0]
      - service: notify.send_message
        data:
          entity_id: notify.telegram_vtel
          message: >
            ⚠ {{ now().strftime('%Y-%m-%d %H:%M') }}
            | 1 Mains voltage (sensor) is missing
            | ip: {{ states('sensor.myip') }}
            | power: {{ states('sensor.0xa46dd4fffe4f985d_power') }}
            | battery: {{ states('sensor.delta_2_max_battery_level') }}%
      - repeat:
          count: 3
          sequence:
            - service: light.turn_on
              entity_id: light.gateway_light_7811dcb245b2
              data:
                brightness: 255
                rgb_color: [255, 0, 0]
            - delay: "00:01:00"

  - alias: "UPS mirror OB/OL to helper"
    id: ups_mirror_ob_ol
    initial_state: true
    mode: queued
    trace:
      stored_traces: 20
    trigger:
      - platform: state
        entity_id: sensor.ups_status_data
    action:
      - choose:
          # If UPS status contains OB -> set helper ON (we are on battery)
          - conditions: >
              {{ trigger.to_state is not none and 'OB' in trigger.to_state.state }}
            sequence:
              - service: input_boolean.turn_on
                target:
                  entity_id: input_boolean.ups_on_battery
          # If UPS status contains OL -> set helper OFF (we are on mains)
          - conditions: >
              {{ trigger.to_state is not none and 'OL' in trigger.to_state.state }}
            sequence:
              - service: input_boolean.turn_off
                target:
                  entity_id: input_boolean.ups_on_battery

  - alias: "Notify when UPS goes on AC"
    id: notify_when_ups_goes_on_ac_v2
    initial_state: true
    mode: single
    trace:
      stored_traces: 20
    trigger:
      - platform: state
        entity_id: input_boolean.ups_on_battery
        from: "on"        # was on battery
        to: "off"         # now on mains
        for: "00:01:00"   # mains stable for 1 minute
    action:
      - wait_template: >
          {{ states('sensor.myip') not in ['unknown', 'unavailable', 'None', ''] }}
        timeout: "00:02:00"
        continue_on_timeout: true

      - service: notify.send_message
        data:
          entity_id: notify.telegram_vtel
          message: >
            ⚡ {{ now().strftime('%Y-%m-%d %H:%M') }}
            | 2 Mains voltage restored
            | ip: {{ states('sensor.myip') }}

  - alias: 'Notify when EcoFlow Delta 2 battery low'
    id: notify_ecoflow_delta2_battery_low
    initial_state: true
    mode: restart
    trigger:
      - platform: numeric_state
        entity_id: sensor.delta_2_max_battery_level
        below: 21
        above: 10
        for: "00:01:00"
      - platform: numeric_state
        entity_id: sensor.delta_2_max_battery_level
        below: 11
        above: 5
        for: "00:01:00"
      - platform: numeric_state
        entity_id: sensor.delta_2_max_battery_level
        below: 6
        above: 1
        for: "00:01:00"
      - platform: numeric_state
        entity_id: sensor.delta_2_max_battery_level
        below: 2
        for: "00:00:30"
    action:
      - service: notify.send_message
        data:
          entity_id: notify.telegram_vtel
          message: >
            🪫⚡ {{ now().strftime('%Y-%m-%d %H:%M') }}
            | EcoFlow Delta 2 battery low!
            | Battery level: {{ states('sensor.delta_2_max_battery_level') }}%

  - alias: 'Start power outage timer'
    id: start_power_outage_timer
    initial_state: true
    mode: single
    trigger:
      - platform: numeric_state
        entity_id: sensor.0xa46dd4fffe4f985d_power
        below: 10
        for: "00:01:00"
      - platform: homeassistant
        event: start
        id: ha_start
    condition:
      - condition: template
        value_template: >
          {{ states('input_number.power_outage_timestamp') | float(0) == 0 }}
      - condition: template
        value_template: >
          {{ states('sensor.0xa46dd4fffe4f985d_power') | float(999) < 10 }}
    action:
      - service: input_number.set_value
        target:
          entity_id: input_number.power_outage_timestamp
        data:
          value: "{{ now().timestamp() | int }}"

  - alias: 'Stop power outage timer'
    id: stop_power_outage_timer
    initial_state: true
    mode: single
    trigger:
      - platform: numeric_state
        entity_id: sensor.0xa46dd4fffe4f985d_power
        above: 180
        for: "00:01:00"
      - platform: homeassistant
        event: start
        id: ha_start
    condition:
      - condition: template
        value_template: >
          {{ states('input_number.power_outage_timestamp') | float(0) > 0 }}
      - condition: template
        value_template: >
          {{ states('sensor.0xa46dd4fffe4f985d_power') | float(0) > 180 }}
    action:
      - service: notify.send_message
        data:
          entity_id: notify.telegram_vtel
          message: >
            ⚡ {{ now().strftime('%Y-%m-%d %H:%M') }}
            | 1 Mains voltage restored
            | ip: {{ states('sensor.myip') }}
            | power: {{ states('sensor.0xa46dd4fffe4f985d_power') }}W
            | outage duration: {{ states('sensor.power_outage_duration_formatted') }}
            | battery: {{ states('sensor.delta_2_max_battery_level') }}%

      - service: input_number.set_value
        target:
          entity_id: input_number.power_outage_timestamp
        data:
          value: 0

      - service: script.ups_power_restore_cleanup

group:
  power_restore_targets:
    name: Power restore targets
    entities:
      - light.wc_spots
      - light.kitchen_lamp
      - light.balcony_strip
      - light.gateway_light_7811dcb245b2
      - climate.ac_living_room_climate
      - climate.ac_master_bedroom_climate
      - climate.ac_bedroom_climate

script:
  ups_power_restore_cleanup:
    alias: UPS power restore cleanup
    mode: single
    sequence:
      - repeat:
          count: 3
          sequence:
            - service: homeassistant.turn_off
              target:
                entity_id: group.power_restore_targets
            - delay: "00:02:00"
