script:
  # dummy
  reboot_ha1:
    alias: "Reboot HA1"
    sequence:
      - delay: '00:00:02'

automation:
  - alias: 'Notify when UPS goes on battery'
    initial_state: true
    trigger:
      - platform: state
        entity_id: sensor.ups_status_data
    condition:
      - condition: template
        value_template: "{{ 'OL' in trigger.from_state.state and 'OB' in trigger.to_state.state }}"
    action:
      - delay: '00:02:00'
      - service: notify.telegram
        data:
          message: "\U00002620 {{ states('sensor.time_date') }} | Mains voltage is missinig | ip: {{ states('sensor.myip') }}"

  - alias: 'Notify when UPS goes on ac'
    initial_state: true
    trigger:
      - platform: state
        entity_id: sensor.ups_status_data
    condition:
      - condition: template
        value_template: "{{ 'OB' in trigger.from_state.state and 'OL' in trigger.to_state.state }}"
    action:
      - delay: '00:03:00'
      - service: notify.telegram
        data:
          message: "\U000026A1 {{ states('sensor.time_date') }} | Mains voltage restored | ip: {{ states('sensor.myip') }}"
      - delay: '00:04:00'
      - service: light.turn_off
        entity_id:
          - group.living_room_spot_left


