script:
  rf_br_3_sb_rf:
    alias: "rf br3 sb rf"
    sequence:
      - service: esphome.sonoff_rf_br_3_send_rf_code
        data:
          sync: !secret rf1_sync
          low:  !secret rf1_low
          high: !secret rf1_high
          code: !secret rf1_code
  rf_br_3_gate1:
    alias: "rf br3 gate1"
    sequence:
      - service: esphome.sonoff_rf_br_3_send_rf_code
        data:
          sync: !secret rf2_sync
          low:  !secret rf2_low
          high: !secret rf2_high
          code: !secret rf2_code
  rf_br_3_gate2:
    alias: "rf br3 gate2"
    sequence:
      - service: esphome.sonoff_rf_br_3_send_rf_code
        data:
          sync: !secret rf3_sync
          low:  !secret rf3_low
          high: !secret rf3_high
          code: !secret rf3_code
  rf_br_3_key4:
    alias: "rf br3 key4"
    sequence:
      - service: esphome.sonoff_rf_br_3_send_rf_code
        data:
          sync: !secret rf4_sync
          low:  !secret rf4_low
          high: !secret rf4_high
          code: !secret rf4_code

binary_sensor:
  - platform: template
    sensors:
      rf_br_3_sb_rf:
        friendly_name: "rf br 3 sb rf"
        value_template: false
      rf_br_3_gate1:
        friendly_name: "rf br 3 gate1"
        value_template: false
      rf_br_3_gate2:
        friendly_name: "rf br 3 gate2"
        value_template: false
      rf_br_3_key4:
        friendly_name: "rf br 3 key4"
        value_template: false

automation:
  - alias: "rf_br3_sb_rf"
    initial_state: 'on'
    trigger:
      platform: event
      event_type: esphome.rf_code_received
      event_data:
        sync: !secret rf1_sync
        low:  !secret rf1_low
        high: !secret rf1_high
        code: !secret rf1_code
    action:
      - service: python_script.set_state
        data_template:
          entity_id: binary_sensor.rf_br_3_sb_rf
          state: ON
      - service: notify.telegram
        data:
          message: "rf_br_3_sb_rf"
