template:
  - sensor:
      - name: "Front Door Last Activity Date"
        icon: "mdi:clock"
        state: "{{ as_timestamp(state_attr('sensor.front_door_last_activity', 'created_at'), default=0) | timestamp_custom('%H:%M %d-%m-%Y') }}"

      - name: "Front Door Last Ding Date"
        icon: "mdi:clock"
        state: "{{ as_timestamp(state_attr('sensor.front_door_last_ding', 'created_at'), default=0) | timestamp_custom('%H:%M %d-%m-%Y') }}"

      - name: "Front Door Last Motion Date"
        icon: "mdi:clock"
        state: "{{ as_timestamp(state_attr('sensor.front_door_last_motion', 'created_at'), default=0) | timestamp_custom('%H:%M %d-%m-%Y') }}"

#downloader:
#  download_dir: downloads

automation:
  - alias: "Ring DoorBell"
    initial_state: true
    trigger:
      platform: state
      entity_id: event.front_door_ding
#      entity_id: binary_sensor.front_door_ding
#      to: 'on'
    action:
      - service: notify.send_message
        data:
          entity_id: notify.telegram_vtel
          message: "\U0001F515 The doorbell rings !!!"

  - alias: "Ring Video Download"
    initial_state: true
    trigger:
#      platform: template
#      value_template: "{{ is_state_attr('sensor.front_door_last_activity', 'recording_status', 'ready') }}"
      - trigger: state
        entity_id: binary_sensor.front_doorbell_ding
        to: "on"
    actions:
      - action: downloader.download_file
        data:
          url: "{{ state_attr('camera.front_door', 'video_url') }}"
          subdir: "ring_{{ now().strftime('%Y_%m_%d') }}"
          filename: "motion_{{ now().strftime('%Y_%m_%d_%H_%M') }}.mpg"
