vacuum:
  - platform: xiaomi_miio
    host: !secret xiaomi_vacuum_ip
    token: !secret xiaomi_vacuum_token

input_select:
  vacuum_room:
    name: "Choose a room to clean"
    options:
      - Select Room
      - All Except Balcony
      - Entryway
      - Hallway
      - Kitchen
      - Living Room
      - Master Bedroom
      - Bedroom
    initial: Select Room

input_boolean:
  vacuum_schedule:
    name: "Регулярная уборка роботом"
    icon: "mdi:timer"
  vacuum_notification:
    name: "Сообщения от робота"
    icon: "mdi:bell"

sensor:
  - platform: template
    sensors:
      vacuum_cleaner_status_sensor:
        friendly_name: "Vacuum Cleaner Status Sensor"
        value_template: "{{ states.vacuum.xiaomi_vacuum_cleaner.attributes.status }}"

      vacuum_cleaner_error_sensor:
        friendly_name: "Vacuum Cleaner Error Sensor"
        value_template: >
          {% if states.vacuum.xiaomi_vacuum_cleaner.attributes.error is defined %}
            {{states.vacuum.xiaomi_vacuum_cleaner.attributes.error}}
          {% else %}
            No Error
          {% endif %}

  - platform: mqtt
    state_topic: "valetudo/rockrobo/state"
    json_attributes_topic: "valetudo/rockrobo/map_data_parsed"
    name: xiaomi_map
    value_template: 'OK'
    scan_interval: 5

automation:
  - alias: "Vacuum Time Clean 1"
    initial_state: 'on'
    trigger:
      - platform: time
        at: '13:00'
    condition:
      - condition: state
        entity_id: input_boolean.vacuum_schedule
        state: 'on'
      - condition: time
        weekday:
          - tue
          - thu
    action:
      - service: script.turn_on
        entity_id: script.vacuum_all_except_balcony

  - alias: "Vacuum Time Clean 2"
    initial_state: 'on'
    trigger:
      - platform: time
        at: '13:00'
    condition:
      - condition: state
        entity_id: input_boolean.vacuum_schedule
        state: 'on'
      - condition: time
        weekday:
          - mon
          - wed
          - fri
    action:
      - service: script.turn_on
        entity_id: script.vacuum_living_room

  - alias: "Vacuum Cleaning"
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: vacuum.xiaomi_vacuum_cleaner
        to: 'cleaning'
    condition:
      - condition: state
        entity_id: input_boolean.vacuum_notification
        state: 'on'
    action:
      - service: notify.telegram
        data:
          message: "Пылесос начал уборку"

  - alias: "Vacuum Returning"
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: vacuum.xiaomi_vacuum_cleaner
        to: 'returning'
    condition:
      - condition: state
        entity_id: input_boolean.vacuum_notification
        state: 'on'
    action:
       - service: notify.telegram
         data_template:
           message: "Пылесос завершил уборку и возвращается на станцию. Время уборки: {{states.vacuum.xiaomi_vacuum_cleaner.attributes.cleaning_time}} минут. Общая площадь уборки: {{states.vacuum.xiaomi_vacuum_cleaner.attributes.cleaned_area}} м²"

  - alias: "Vacuum Docked"
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: vacuum.xiaomi_vacuum_cleaner
        to: 'docked'
    condition:
      - condition: state
        entity_id: input_boolean.vacuum_notification
        state: 'on'
    action:
      - service: notify.telegram
        data:
          message: "Пылесос прибыл на станцию и заряжается"

  - alias: "Vacuum Cleaner Error"
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: sensor.vacuum_cleaner_status_sensor
        to: 'Error'
      - platform: state
        entity_id: sensor.vacuum_cleaner_status_sensor
        to: 'In Error'
      - platform: state
        entity_id: sensor.vacuum_cleaner_status_sensor
        to: 'Charging Error'
    action:
      - service: notify.telegram
        data:
          message: >
            {% if is_state('sensor.vacuum_cleaner_error_sensor', 'No Error')  %}
              {{states.vacuum.xiaomi_vacuum_cleaner.attributes.status}}
            {% else %}
              {{states.sensor.vacuum_cleaner_error_sensor.state}}
            {% endif %}

  - alias: "Vacuum Cleaner Error Solved"
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: sensor.vacuum_cleaner_error_sensor
        to: 'No Error'
    condition:
      condition: template
      value_template: "{{ states.sensor.ha_uptime.state  | int > 10 }}"
    action:
      - service: notify.telegram
        data:
          message: "Пылесос вне опасности"

  - alias: "Start Cleaning Room"
    initial_state: 'on'
    hide_entity: true
    trigger:
      - platform: state
        entity_id: input_select.vacuum_room
        from: 'Select Room'
    action:
      - service: script.turn_on
        data_template:
          entity_id: >
            {% if is_state("input_select.vacuum_room", "All Except Balcony") %}
             script.vacuum_all_except_balcony
            {% elif is_state("input_select.vacuum_room", "Entryway") %}
              script.vacuum_entryway
            {% elif is_state("input_select.vacuum_room", "Hallway") %}
              script.vacuum_hallway
            {% elif is_state("input_select.vacuum_room", "Kitchen") %}
              script.vacuum_kitchen
            {% elif is_state("input_select.vacuum_room", "Living Room") %}
              script.vacuum_living_room
            {% elif is_state("input_select.vacuum_room", "Master Bedroom") %}
              script.vacuum_master_bedroom
            {% elif is_state("input_select.vacuum_room", "Bedroom") %}
              script.vacuum_bedroom
            {% endif %}
      - service: input_select.select_option
        entity_id: input_select.vacuum_room
        data_template:
          option: 'Select Room'

  - alias: "Hallway Button Click Single"
    initial_state: 'on'
    trigger:
      platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: binary_sensor.switch_158d0002e22617
        click_type: single
    action:
      - service: script.turn_on
        entity_id: script.vacuum_entryway

  - alias: "Hallway Button Click Double"
    initial_state: 'on'
    trigger:
      platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: binary_sensor.switch_158d0002e22617
        click_type: double
    action:
      - service: script.turn_on
        entity_id: script.vacuum_hallway

script:
  vacuum_all_except_balcony:
    alias: "Clean Up All Except Balcony"
    sequence:
      - service: vacuum.send_command
        data:
          entity_id: vacuum.xiaomi_vacuum_cleaner
          command: app_zoned_clean
#         params: [ [32705,32955,37175,35580,1], [31035,31320,32875,34525,2], [33320,28625,37140,32785,1], [31170,27155,32910,31455,1], [33045,25145,37345,28385,1], [28860,27215,31260,28265,1], [24615,25215,28765,28225,1] ]
          params: [ [32705,32955,37175,35580,2], [31035,31320,32875,34525,2], [33320,28625,37140,32785,2], [31170,27155,32910,31455,2], [33045,25145,37345,28385,2]]
      - condition: state
        entity_id: input_boolean.vacuum_notification
        state: 'on'
      - service: notify.telegram
        data:
          message: "Уборка Всей Квартиры Кроме Балкона"

  vacuum_master_bedroom:
    alias: "Clean Up Master Bedroom"
    sequence:
      - service: vacuum.send_command
        data:
          entity_id: vacuum.xiaomi_vacuum_cleaner
          command: app_zoned_clean
          params: [ [33045,25145,37345,28385,1] ]
      - condition: state
        entity_id: input_boolean.vacuum_notification
        state: 'on'
      - service: notify.telegram
        data:
          message: "Уборка Главной Спальни"

  vacuum_bedroom:
    alias: "Clean Up Bedroom"
    sequence:
      - service: vacuum.send_command
        data:
          entity_id: vacuum.xiaomi_vacuum_cleaner
          command: app_zoned_clean
          params: [ [24555,25215,28715,28250,1] ]
      - condition: state
        entity_id: input_boolean.vacuum_notification
        state: 'on'
      - service: notify.telegram
        data:
           message: "Уборка Спальни"

  vacuum_entryway:
    alias: "Clean Up Entryway"
    sequence:
      - service: vacuum.send_command
        data:
          entity_id: vacuum.xiaomi_vacuum_cleaner
          command: app_zoned_clean
          params: [ [31035,31320,32875,34525,2] ]
      - condition: state
        entity_id: input_boolean.vacuum_notification
        state: 'on'
      - service: notify.telegram
        data:
           message: "Уборка Прихожей"

  vacuum_hallway:
    alias: "Clean Up Hallway"
    sequence:
      - service: vacuum.send_command
        data:
          entity_id: vacuum.xiaomi_vacuum_cleaner
          command: app_zoned_clean
          params: [ [31034,31317,32875,34523,2], [31170,27155,32910,31455,1], [28680,27155,31270,28145,1] ]
      - condition: state
        entity_id: input_boolean.vacuum_notification
        state: 'on'
      - service: notify.telegram
        data:
           message: "Уборка Коридора"

  vacuum_kitchen:
    alias: "Clean Up Kitchen"
    sequence:
      - service: vacuum.send_command
        data:
          entity_id: vacuum.xiaomi_vacuum_cleaner
          command: app_zoned_clean
          params: [ [32705,32955,37175,35580,2] ]
      - condition: state
        entity_id: input_boolean.vacuum_notification
        state: 'on'
      - service: notify.telegram
        data:
           message: "Уборка Кухни"

  vacuum_living_room:
    alias: "Clean Up Living Room"
    sequence:
      - service: vacuum.send_command
        data:
          entity_id: vacuum.xiaomi_vacuum_cleaner
          command: app_zoned_clean
          params: [ [33320,28625,37140,32785,2] ]
      - condition: state
        entity_id: input_boolean.vacuum_notification
        state: 'on'
      - service: notify.telegram
        data:
           message: "Уборка Гостиной"

  vacuum_reset_main_brush:
    alias: "Reset Main Brush"
    sequence:
      - service: vacuum.send_command
        data_template:
          entity_id: vacuum.xiaomi_vacuum_cleaner
          command: reset_consumable
          params: main_brush_work_time

  vacuum_reset_side_brush:
    alias: "Reset Side Brush"
    sequence:
      - service: vacuum.send_command
        data_template:
          entity_id: vacuum.xiaomi_vacuum_cleaner
          command: reset_consumable
          params: side_brush_work_time

  vacuum_reset_filter:
    alias: "Reset Filter"
    sequence:
      - service: vacuum.send_command
        data_template:
          entity_id: vacuum.xiaomi_vacuum_cleaner
          command: reset_consumable
          params: filter_work_time

  vacuum_reset_sensor:
    alias: "Reset Sensor"
    sequence:
      - service: vacuum.send_command
        data_template:
          entity_id: vacuum.xiaomi_vacuum_cleaner
          command: reset_consumable
          params: sensor_dirty_time

