automation:
  - alias: zigbee2mqtt_z2m_bridge_status
    initial_state: true
    trigger:
      - platform: state
        entity_id: binary_sensor.zigbee2mqtt_bridge_connection_state
    action:
      - service: notify.telegram
        data:
          message: >
            {%if is_state('binary_sensor.zigbee2mqtt_bridge_connection_state','on')%}{{"\U00002705"}} Z2M is online!
            {%else%}{{"\U0000274C"}} Attention! Z2M is offline!
            {%endif%}

sensor:
  - platform: rest
    name: "Z2M Latest"
    resource: https://api.github.com/repos/Koenkk/zigbee2mqtt/releases/latest
    value_template: "{{ value_json.tag_name }}"
    scan_interval: 1800
