- platform: rest
  name: "HA Latest"
  resource: https://version.home-assistant.io/stable.json
  value_template: "{{ value_json.homeassistant.default }}"
  scan_interval: 1800

- platform: rest
  name: "HA Beta"
  resource: https://version.home-assistant.io/beta.json
  value_template: "{{ value_json.homeassistant.default }}"
  scan_interval: 1800

- platform: rest
  resource_template: "{{ states('input_text.ha1_url') }}api/states/sensor.ha_uptime"
  name: ha1_uptime
  device_class: timestamp
  force_update: true
  headers:
    authorization: !secret ha1_token
  value_template: >
    {% if states('input_text.ha1_url') not in ['unknown', 'unavailable'] and value_json is defined and value_json.state not in ['unknown', 'unavailable', None] %}
      {{ (as_timestamp(now()) - (value_json.state | float(default=0) * 60)) | as_datetime }}
    {% endif %}

- platform: rest
  name: ha2_uptime
  resource_template: "{{ states('input_text.ha2_url') }}api/states/sensor.ha_uptime"
  device_class: timestamp
  force_update: true
  headers:
    authorization: !secret ha2_token
  value_template: >
    {% if states('input_text.ha2_url') not in ['unknown', 'unavailable'] and value_json is defined and value_json.state not in ['unknown', 'unavailable', None] %}
      {{ (as_timestamp(now()) - (value_json.state | float(default=0) * 60)) | as_datetime }}
    {% endif %}

- platform: rest
  name: has_uptime
  resource_template: "{{ states('input_text.has_url') }}api/states/sensor.ha_uptime"
  device_class: timestamp
  force_update: true
  headers:
    authorization: !secret has_token
  value_template: >
    {% if states('input_text.has_url') not in ['unknown', 'unavailable'] and value_json is defined and value_json.state not in ['unknown', 'unavailable', None] %}
      {{ (as_timestamp(now()) - (value_json.state | float(default=0) * 60)) | as_datetime }}
    {% endif %}

- platform: rest
  name: ha_fazenda_uptime
  resource_template: "{{ states('input_text.ha_fazenda_url') }}api/states/sensor.ha_uptime"
  device_class: timestamp
  force_update: true
  headers:
    authorization: !secret ha_fazenda_token
  value_template: >
    {% if states('input_text.ha_fazenda_url') not in ['unknown', 'unavailable'] and value_json is defined and value_json.state not in ['unknown', 'unavailable', None] %}
      {{ (as_timestamp(now()) - (value_json.state | float(default=0) * 60)) | as_datetime }}
    {% endif %}
