- platform: systemmonitor
  resources:
    - type: last_boot
    - type: processor_use
    - type: memory_use_percent
    - type: swap_use_percent
    - type: disk_use_percent
      arg: /

- platform: command_line
  name: "CPU Temperature"
  command: 'cat /sys/class/thermal/thermal_zone0/temp'
  unit_of_measurement: "°C"
  value_template: "{{ value | multiply(0.001) }}"

- platform: command_line
  name: "HA Init"
  command: 'cat /config/home-assistant.log | grep -o "initialized[[:space:]]in[[:space:]][0-9]\+.[0-9]\+" | grep -o "[0-9]\+.[0-9]\+$" || echo -1'
  scan_interval: 180
  unit_of_measurement: "sec"

- platform: version
  name: "HA Current"
  scan_interval: 1800

- platform: uptime
  name: "HA Online"

- platform: template
  sensors:
    ha_uptime:
      friendly_name: HA Uptime
      icon_template: mdi:clock
      value_template: "{{ ((as_timestamp(now()) | int - as_timestamp(states('sensor.ha_online')) | int) / 60 ) | int }}"
      unit_of_measurement: minutes

- platform: rest
  resource: https://version.home-assistant.io/stable.json
  name: "HA Latest"
  value_template: "{{ value_json.homeassistant.default }}"
  scan_interval: 1800

- platform: rest
  resource: https://version.home-assistant.io/beta.json
  name: "HA Beta"
  value_template: "{{ value_json.homeassistant.default }}"
  scan_interval: 1800

- platform: rest
  resource_template: "{{ states('input_text.ha1_url') }}api/states/sensor.ha_uptime"
  name: ha1_uptime
  device_class: timestamp
  force_update: true
  headers:
    authorization: !secret ha1_token
  value_template: "{{ (as_timestamp(now()) - (value_json.state | float * 60)) | timestamp_custom('%Y-%m-%d %H:%M:%S%z', true) }}"
  json_attributes:
    - state

- platform: rest
  resource_template: "{{ states('input_text.ha2_url') }}api/states/sensor.ha_uptime"
  name: ha2_uptime
  device_class: timestamp
  force_update: true
  headers:
    authorization: !secret ha2_token
  value_template: "{{ (as_timestamp(now()) - (value_json.state | float * 60)) | timestamp_custom('%Y-%m-%d %H:%M:%S%z', true) }}"
  json_attributes:
    - state

- platform: rest
  resource_template: "{{ states('input_text.ha_fazenda_url') }}api/states/sensor.ha_uptime"
  name: ha_fazenda_uptime
  device_class: timestamp
  force_update: true
  headers:
    authorization: !secret ha_fazenda_token
  value_template: "{{ (as_timestamp(now()) - (value_json.state | float * 60)) | timestamp_custom('%Y-%m-%d %H:%M:%S%z', true) }}"
  json_attributes:
    - state

- platform: template
  sensors:
    instance_name:
      value_template: !secret home_name

