substitutions:
  device_name: nodemcu_3

esphome:
  name: ${device_name}
  platform: ESP32
  board: nodemcu-32s

wifi:
  output_power: 20dB
  fast_connect: true
  ssid: !secret wifi_ssid_3
  password: !secret wifi_pass_3
  manual_ip:
    static_ip: 192.168.1.46
    gateway: 192.168.1.1
    subnet: 255.255.255.0
    dns1: 192.168.1.1
    dns2: 1.1.1.1

time:
  - platform: homeassistant

logger:
api:
ota:
captive_portal:

esp32_ble_tracker:
  scan_parameters:
#   interval: 320ms
#   window: 30ms
    interval: 512ms
    window: 48ms

dallas:
  - pin: GPIO13
#  - pin: 13

binary_sensor:
  - platform: status
    name: ${device_name}_status

sensor:
  - platform: uptime
    name: ${device_name}_uptime
    icon: mdi:timer-outline

  - platform: wifi_signal
    name: ${device_name}_wifi_signal
    icon: mdi:wifi

  - platform: xiaomi_lywsdcgq
    mac_address: !secret kitchen_bt_mac
    temperature:
      name: kitchen_bt_temperature
    humidity:
      name: kitchen_bt_humidity
    battery_level:
      name: kitchen_bt_battery_level

  - platform: xiaomi_lywsdcgq
    mac_address: !secret living_room_bt_mac
    temperature:
      name: living_room_bt_temperature
    humidity:
      name: living_room_bt_humidity
    battery_level:
      name: living_room_bt_battery_level

  - platform: xiaomi_hhccjcy01
    mac_address: !secret miflora1
    temperature:
      name: mf1_temperature
    moisture:
      name: mf1_moisture
    illuminance:
      name: mf1_illuminance
    conductivity:
      name: mf1_soil

  - platform: xiaomi_hhccjcy01
    mac_address: !secret miflora2
    temperature:
      name: mf2_temperature
    moisture:
      name: mf2_moisture
    illuminance:
      name: mf2_illuminance
    conductivity:
      name: mf2_soil

#  - platform: xiaomi_hhccjcy01
#    mac_address: !secret miflora3
#    temperature:
#      name: mf3_temperature
#    moisture:
#      name: mf3_moisture
#    illuminance:
#      name: mf3_illuminance
#    conductivity:
#      name: mf3_soil

  - platform: dallas
    address: !secret dallas_2
    name: ${device_name}_outdoor_temperature

text_sensor:
  - platform: version
    name: ${device_name}_esphome_version
    icon: mdi:information-outline

  - platform: wifi_info
    ip_address:
      name: ${device_name}_ip_address
      icon: mdi:ip-network
    ssid:
      name: ${device_name}_connected_ssid
      icon: mdi:access-point

switch:
  - platform: restart
    name: ${device_name}_restart
    icon: mdi:restart
