substitutions:
  device_name: nodemcu-3
  friendly_name: "NodeMCU 3"

esphome:
  name: ${device_name}
  friendly_name: "${friendly_name}"
  platform: ESP32
  board: nodemcu-32s

ota:
  platform: esphome

wifi:
  output_power: 18dB
  fast_connect: true
  ssid: !secret wifi_ssid_3
  password: !secret wifi_pass_3
  manual_ip:
    static_ip: 192.168.1.46
    gateway: 192.168.1.1
    subnet: 255.255.255.0
    dns1: 192.168.1.1
    dns2: 1.1.1.1

time:
  - platform: homeassistant

logger:
api:
captive_portal:

esp32_ble_tracker:
  scan_parameters:
#   interval: 320ms
#   window: 30ms
    interval: 512ms
    window: 48ms

one_wire:
  - platform: gpio
    pin: 13

binary_sensor:
  - platform: status
    name: Status

sensor:
  - platform: uptime
    name: Uptime
    icon: mdi:timer-outline

  - platform: wifi_signal
    name: WiFi Signal
    icon: mdi:wifi

  - platform: xiaomi_lywsdcgq
    mac_address: !secret kitchen_bt_mac
    temperature:
      name: kitchen_bt_temperature
    humidity:
      name: kitchen_bt_humidity
    battery_level:
      name: kitchen_bt_battery_level

  - platform: xiaomi_lywsdcgq
    mac_address: !secret living_room_bt_mac
    temperature:
      name: living_room_bt_temperature
    humidity:
      name: living_room_bt_humidity
    battery_level:
      name: living_room_bt_battery_level

  - platform: xiaomi_hhccjcy01
    mac_address: !secret miflora1
    temperature:
      name: mf1_temperature
    moisture:
      name: mf1_moisture
    illuminance:
      name: mf1_illuminance
    conductivity:
      name: mf1_soil

  - platform: xiaomi_hhccjcy01
    mac_address: !secret miflora2
    temperature:
      name: mf2_temperature
    moisture:
      name: mf2_moisture
    illuminance:
      name: mf2_illuminance
    conductivity:
      name: mf2_soil

#  - platform: xiaomi_hhccjcy01
#    mac_address: !secret miflora3
#    temperature:
#      name: mf3_temperature
#    moisture:
#      name: mf3_moisture
#    illuminance:
#      name: mf3_illuminance
#    conductivity:
#      name: mf3_soil

  - platform: dallas_temp
    name: Outdoor Temperature
    address: !secret dallas_2
    update_interval: 60s
    unit_of_measurement: "°C"

text_sensor:
  - platform: version
    name: ESPHome Version
    icon: mdi:information-outline
    hide_timestamp: true

  - platform: wifi_info
    ip_address:
      name: IP Address
      icon: mdi:ip-network
    ssid:
      name: Connected SSID
      icon: mdi:access-point

switch:
  - platform: restart
    name: Restart
    icon: mdi:restart

