substitutions:
  device_name: power-strip-1
  friendly_name: "Power Strip 1"

esphome:
  name: ${device_name}
  friendly_name: "${friendly_name}"
  platform: ESP8266
  board: esp8285
  esp8266_restore_from_flash: true

ota:
  platform: esphome

wifi:
  output_power: 17dB
  ssid: !secret wifi_ssid_3
  password: !secret wifi_pass_3
  manual_ip:
    static_ip: 192.168.1.41
    gateway: 192.168.1.1
    subnet: 255.255.255.0
    dns1: 192.168.1.1
    dns2: 1.1.1.1

logger:
  level: DEBUG

api:
captive_portal:

time:
  - platform: homeassistant

binary_sensor:
  - platform: status
    name: Status

  - platform: gpio
    pin: 3
    name: Button
    filters:
      - invert
    on_multi_click:
    - timing:
        - ON for at most 0.4s
        - OFF for at most 0.4s
        - ON for at most 0.4s
        - OFF for at most 0.4s
        - ON for at most 0.4s
        - OFF for at most 0.4s
        - ON for at most 0.4s
        - OFF for at least 0.2s
      then:
        - logger.log: "Quarter Click - socket 4"
        - switch.toggle: relay4
    - timing:
        - ON for at most 0.4s
        - OFF for at most 0.4s
        - ON for at most 0.4s
        - OFF for at most 0.4s
        - ON for at most 0.4s
        - OFF for at least 0.2s
      then:
        - logger.log: "Tripple Click - socket 3"
        - switch.toggle: relay3
    - timing:
        - ON for at most 0.4s
        - OFF for at most 0.4s
        - ON for at most 0.4s
        - OFF for at least 0.2s
      then:
        - logger.log: "Double Click - socket 2"
        - switch.toggle: relay2
    - timing:
        - ON for at most 0.5s
        - OFF for at least 0.4s
      then:
        - logger.log: "Single Click - socket 1"
        - switch.toggle: relay1
    - timing:
        - ON for 0.6s to 3s
        - OFF for at least 0.3s
      then:
        - logger.log: "Single Long Click - USB"
        - switch.toggle: relay_usb

sensor:
  - platform: uptime
    name: Uptime
    icon: mdi:timer-outline

  - platform: wifi_signal
    name: WiFi Signal
    icon: mdi:wifi

text_sensor:
  - platform: version
    name: ESPHome Version
    icon: mdi:information-outline
    hide_timestamp: true

  - platform: wifi_info
    ip_address:
      name: IP Address
      icon: mdi:ip-network
    ssid:
      name: Connected SSID
      icon: mdi:access-point

status_led:
  pin: 1

switch:
  - platform: restart
    name: Restart
    icon: mdi:restart

  - platform: gpio
    pin: 5
    name: Relay1
    icon: mdi:power-socket-eu
    id: relay1
    restore_mode: ALWAYS_ON
    #restore_mode: ALWAYS_OFF

  - platform: gpio
    pin: 4
    name: Relay2
    icon: mdi:power-socket-eu
    id: relay2
    #restore_mode: ALWAYS_OFF

  - platform: gpio
    pin: 12
    name: Relay3
    icon: mdi:power-socket-eu
    id: relay3
    #restore_mode: ALWAYS_OFF

  - platform: gpio
    pin: 13
    name: Relay4
    icon: mdi:power-socket-eu
    id: relay4
    #restore_mode: ALWAYS_OFF

  - platform: gpio
    pin:
      number: 14
      inverted: yes
#   pin: 14
    name: Relay USB
    icon: mdi:usb
    id: relay_usb
    restore_mode: ALWAYS_ON
