# Sonoff Pow R2
substitutions:
  device_name: sonoff-pump
  friendly_name: "Sonoff Pump"
  update_interval: 60s

esphome:
  name: ${device_name}
  friendly_name: "${friendly_name}"

esp8266:
  board: esp01_1m

ota:
  platform: esphome

wifi:
  output_power: 20dB
  ssid: !secret wifi_ssid_3
  password: !secret wifi_pass_3
  #use_address: 192.168.1.7
  manual_ip:
    static_ip: 192.168.1.7
    gateway: 192.168.1.1
    subnet: 255.255.255.0
    dns1: 192.168.1.1
    dns2: 1.1.1.1

time:
  - platform: homeassistant

api:
captive_portal:

logger:
  baud_rate: 0

uart:
  rx_pin: RX
  baud_rate: 4800
  parity: EVEN

binary_sensor:
  - platform: status
    name: Status

  - platform: gpio
    name: Button
    pin:
      number: GPIO00
      mode: INPUT_PULLUP
      inverted: true
    on_press:
      - switch.toggle: fakebutton

switch:
  - platform: restart
    name: Restart
    icon: mdi:restart

  - platform: template
    name: Relay
    icon: mdi:water-pump
    optimistic: true
    id: fakebutton
    turn_on_action:
      - switch.turn_on: relay
      - light.turn_on: led
    turn_off_action:
      - switch.turn_off: relay
      - light.turn_off: led

  - platform: gpio
    id: relay
    pin: GPIO12

sensor:
  - platform: uptime
    name: Uptime
    icon: mdi:timer-outline

  - platform: wifi_signal
    name: Wifi Signal
    icon: mdi:wifi

  - platform: cse7766
    current:
      name: Current
      icon: mdi:current-ac
      unit_of_measurement: A
      filters:
        - throttle_average: ${update_interval}
    voltage:
      name: Voltage
      icon: mdi:lightning-bolt-circle
      unit_of_measurement: V
      filters:
        - throttle_average: ${update_interval}
    power:
      id: power
      name: Power
      icon: mdi:flash-outline
      unit_of_measurement: W
      filters:
        - throttle_average: ${update_interval}
      on_value_range:
        - above: 4.0
          then:
            - light.turn_on: led
        - below: 3.0
          then:
            - light.turn_off: led
    #update_interval: 10s

  - platform: total_daily_energy
    name: Daily Energy
    icon: mdi:power-settings
    power_id: power
    filters:
      - multiply: 0.001
    unit_of_measurement: kWh

text_sensor:
  - platform: version
    name: Esphome Version
    icon: mdi:information-outline
    hide_timestamp: true

  - platform: wifi_info
    ip_address:
      name: IP Address
      icon: mdi:ip-network
    ssid:
      name: Connected SSID
      icon: mdi:access-point

output:
  - platform: esp8266_pwm
    id: pow_blue_led
    pin:
      number: GPIO13
      inverted: true

light:
  - platform: monochromatic
    id: led
    name: Blue Led
    output: pow_blue_led


